### ISSUE TITLE
[Feature Request] Whisparr

### ISSUE THREAD

**Issue by pops64** [ManiMatter/decluttarr#111]
I hate to be the only person that enjoys adult fun time :P but I would love to see your script support its API as well.

**Comment by ManiMatter** [comment]
Want to contribute with a PR? ;)

**Comment by pops64** [comment]
:P . I will take a look but my python skills are lacking more a LUA/JS dev

**Comment by pops64** [comment]
I prefer you to do it. You haven't permitted outside access to the necessary files for me to effect the change. And I don't really feel like learning how to build and run local docker images.

**Comment by ManiMatter** [comment]
you dont need to build any images. clone the git to your local machine and run the main.py. 
Then you alter the code in the respective files until you are happy and create a PR.

**Comment by pops64** [comment]
I am running it off a Arch headless server with minimal packages. Which limits my options. I just brute forced it. Since you don't have it set to mount files, I think this is the right term. I just mounted the apps directory to a local host volume and placed all your files in there. It appears to be working correctly. I have gone through and added whipsarr to all necessary files. The API call is the same as Sonarr. I have two stalled files currently for testing purposes I will let your know if it errors out

**Comment by pops64** [comment]
Didn't get to the readme yet. The remove_unmonitored through a code. How I figured that one out. I think main also needs it for version checking. I set it to my current version unless you want something else specified

**Comment by ManiMatter** [comment]
not sure i understand your last post.

version: suggest you put a version that works. can be today's version, for me that's fine.

> The remove_unmonitored through a code. How I figured that one out. 

is that a question how to change it? you need to check the API response form whisparr to understand how to parametrize it. look at sonarr and radarr, and do the corresponding thing for whisparr

**Comment by pops64** [comment]
Sorry I fell asleep ensuring spell check did a good job L(. I recently distro hopped. So now I am just fighting with git to get this pushed to my fork and I then I will make a PR.
