### ISSUE TITLE
Docker gives an "unexpected type map[string]interface {}" error when pulling with the newest compose.yaml

### ISSUE THREAD

**Issue by PronPan** [ManiMatter/decluttarr#116]
This is caused by "FAILED_IMPORT_MESSAGE_PATTERNS:" using a colon instead of "=" like the other variables. The image is able to be pulled fine when correcting that, but it then isn't able to convert the "Not an upgrade for existing" strings to a list. Fixed this by removing the extra indentation and quotes, which changes the entire variable to-

`      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not an upgrade for existing", "Not a Custom Format upgrade for existing"]`
                                         
No issues anymore.

PS: This script is perfect and does exactly what I need. Thank you!!!

**Comment by ManiMatter** [comment]
Hi, thanks for reporting the issue.

I will correct the readme.
