### ISSUE TITLE
Not removing all failed imports

### ISSUE THREAD

**Issue by cliny** [ManiMatter/decluttarr#120]
Hi there,

I have found that failed imports with this message aren't being removed:

"Found matching series via grab history, but release was matched to series by ID. Automatic import is not possible"

Or the radarr equivalent of the message.

I even tried explicitly placing the message in FAILED_IMPORT_MESSAGE_PATTERNS=, to no avail. But otherwise I leave it blank to catch all warnings.

Here is a log:

```
[INFO   ]: ##################################################
[INFO   ]: Decluttarr - Application Started!
[INFO   ]: 
[INFO   ]: Like this app? Thanks for giving it a ⭐ on GitHub!
[INFO   ]: https://github.com/ManiMatter/decluttarr/
[INFO   ]: 
[INFO   ]: *** Current Settings ***
[INFO   ]: Version: v1.45.0
[INFO   ]: Commit: abf6cc7
[INFO   ]: 
[INFO   ]: True | Removing failed downloads (REMOVE_FAILED)
[INFO   ]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[VERBOSE]: > Any imports with a warning flag are considered failed, as no patterns specified (FAILED_IMPORT_MESSAGE_PATTERNS).
[INFO   ]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO   ]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO   ]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO   ]: False | Removing slow downloads (REMOVE_SLOW)
[INFO   ]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO   ]: False | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO   ]: 
[INFO   ]: Running every: 0 days 0 hours 1.0 minutes
[INFO   ]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 1
[INFO   ]: 
[INFO   ]: *** Configured Instances ***
[INFO   ]: Radarr: https://radarr.REDACTED/api/v3
[INFO   ]: Sonarr: https://sonarr.REDACTED/api/v3
[INFO   ]: Lidarr: https://lidarr.REDACTED/api/v1
[INFO   ]: 
[INFO   ]: *** Check Instances ***
[INFO   ]: OK | Radarr
[INFO   ]: OK | Sonarr
[INFO   ]: OK | Lidarr
[INFO   ]: 
[INFO   ]: ##################################################
[INFO   ]: 
[VERBOSE]: --------------------------------------------------
[VERBOSE]: Cleaning queue on Radarr:
[VERBOSE]: >>> Queue is clean.
[VERBOSE]: Cleaning queue on Sonarr:
[VERBOSE]: >>> Queue is clean.
[VERBOSE]: Cleaning queue on Lidarr:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]: 
[VERBOSE]: Queue clean-up complete!
```

I'm not sure what I'm doing wrong?  I'm using the latest stable "linuxserver" containers for everything (sabnzbd, sonarr, etc), updated daily.

Thanks

**Comment by ManiMatter** [comment]
Can you pls post debug logs

1. Switch decluttarr to debug mode (setting LOG_LEVEL: DEBUG)
2. Turn off all remove functions but one where you expect a removal (example: REMOVE_STALLED: True and the rest on False)
3. Let it run until the supposed remove should be trigged
4. Paste the full logs to a pastebin
5. If helpful: Paste a screenshot of qbit and the affected *arr app to a pasteimg

**Comment by cliny** [comment]
> Can you pls post debug logs
> 
>     1. Switch decluttarr to debug mode (setting LOG_LEVEL: DEBUG)
> 
>     2. Turn off all remove functions but one where you expect a removal (example: REMOVE_STALLED: True and the rest on False)
> 
>     3. Let it run until the supposed remove should be trigged
> 
>     4. Paste the full logs to a pastebin
> 
>     5. If helpful: Paste a screenshot of qbit and the affected *arr app to a pasteimg

Debug logs here:
https://pastebin.com/049mWFpi

Sabnzbd screenshot here:
https://pasteimg.com/image/screenshot-20240611-221818.hKmZH

Radarr screenshot here:
https://pasteimg.com/image/screenshot-20240611-221959.hK6ts

Thank you

**Comment by ManiMatter** [comment]
Thank you.

Quite simple really. Your download has     ` "trackedDownloadState":"downloading"`, and the condition decluttar looks for is 
https://github.com/ManiMatter/decluttarr/blob/2ee86d35914d24318b83c0672add7954571c9e0e/src/jobs/remove_failed_imports.py#L21-L23

So the question is.. why doesn't the status read "importPending" or "importFailed"? According to the current status, it seems it's not yet "entirely failed" but yet downloading.

**Comment by cliny** [comment]
I see. I could put this forward to the sonarr team? 

Otherwise, I noticed the 'trackedDownloadStatus' has 'warning'. Is it possible to get an option in decluttarr where any failed imports that have a status as 'warning' will trigger a removal, instead of waiting for the 'importPending' or 'importFailed' state, even if stuck on 'downloading'?

**Comment by ManiMatter** [comment]
That‘d be too broad I‘m afraid. No idea what all the different warnings are (for example: insufficient disk space when importing from disk A to disk B). You Wouldn‘t want to delete from A just because B has insufficient space.

**Comment by cliny** [comment]
It looks like the sonarr team have added an addition state:

https://github.com/Sonarr/Sonarr/pull/6889

**Comment by ManiMatter** [comment]
Once you have the new version installed, pls provide the queue-response from Sonarr.

**Comment by cliny** [comment]
> Once you have the new version installed, pls provide the queue-response from Sonarr.

No worries, I'll do this when I have some time, and report back with the details.


Do you know if radarr will implement this, or if I should raise it with them too?

**Comment by ManiMatter** [comment]
To my knowledge they port it; but if you want confirmation, you need to ask them ;-)

**Comment by cliny** [comment]
> Once you have the new version installed, pls provide the queue-response from Sonarr.

Ok so I've been on sonarr develop (currently 4.0.5.1791) for a few days, trying to get that same import failure, but it hasn't happened yet, trying to force it by randomly downloading a bunch of things.

Anyway, this is the new message and download state:

```
trackedDownload.Warn("Series title mismatch; automatic import is not possible. Check the download troubleshooting entry on the wiki for common causes.");
SetStateToImportBlocked(trackedDownload);
```
Source for the new message and download state: https://github.com/Sonarr/Sonarr/blob/143ccb1e2a18c63cf246368a717c8a9e7732ed8f/src/NzbDrone.Core/Download/CompletedDownloadService.cs#L98

Is this what you wanted?

Also, current queue statuses: https://github.com/Sonarr/Sonarr/blob/143ccb1e2a18c63cf246368a717c8a9e7732ed8f/frontend/src/Activity/Queue/QueueStatus.js

and tracked download states: https://github.com/Sonarr/Sonarr/blob/143ccb1e2a18c63cf246368a717c8a9e7732ed8f/src/NzbDrone.Core/Download/TrackedDownloads/TrackedDownload.cs

Thanks

**Comment by ManiMatter** [comment]
No, I would really want the queue to have the error and see the logs. 

Then we change the code, run it again, snd then we should see the item being removed from your queue.

This way we have a direct before/after comparison and know the change works.

**Comment by cliny** [comment]
Finally got something:
`Found matching series via grab history, but release was matched to series by ID. Automatic import is not possible. See the FAQ for details.`

Log here: https://pastebin.com/jpPuwie6

**Comment by ManiMatter** [comment]
Thanks. I have just added the respective change to the dev-image.
Please can you pull it, set "TEST_RUN=True", run it, and paste the logs again? 
Your queue item should now be detected.

If it works, we'll merge this to the latest image and close this thread.

**Comment by cliny** [comment]
Looking good: https://pastebin.com/BGTNKxk4

thank you

**Comment by cliny** [comment]
Looking good: https://pastebin.com/BGTNKxk4

Different shows, same message tho. (The show in the previous log must have found a match?)

thank you

**Comment by cliny** [comment]
> Thanks. I have just added the respective change to the dev-image. Please can you pull it, set "TEST_RUN=True", run it, and paste the logs again? Your queue item should now be detected.
> 
> If it works, we'll merge this to the latest image and close this thread.

looking good:

https://pastebin.com/1QxB0KRN

thank you

**Comment by ManiMatter** [comment]
Yes looks ok. Will merge to latest now.
