### ISSUE TITLE
[ERROR]: !! Sonarr Error: !! KeyError: 'SONARRMIN_VERSION'

### ISSUE THREAD

**Issue by tegaologe** [ManiMatter/decluttarr#125]
tega@tega:/var/lib/casaos/apps/decluttarr$ docker logs decluttarr
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.0
[INFO]: Commit: 7c2cc97
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.71:7878/api/v3
[INFO]: Sonarr: http://192.168.1.71:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.71:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
KeyError: 'SONARRMIN_VERSION'

**Comment by ManiMatter** [comment]
Could you pls post your docker-compose for decluttarr?

**Comment by tegaologe** [comment]
version: "3.3"
services:
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      - TZ=America/Edmonton
      - PUID=1000
      - PGID=1000
      ## General
      - LOG_LEVEL=INFO
      ## Features 
      - REMOVE_TIMER=10
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True     
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - MIN_DOWNLOAD_SPEED=100
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - IGNORE_PRIVATE_TRACKERS=True
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not an upgrade for existing","Not a Custom Format upgrade for existing"]
      ## Radarr
      - RADARR_URL=http://192.168.1.71:7878
      - RADARR_KEY=29bbb2d74cc14aa5a865dc628ef39d38
      ## Sonarr
      - SONARR_URL=http://192.168.1.71:8989
      - SONARR_KEY=e2f48fd0ec3147b4a46136b0308817fc
      ## qBittorrent
      - QBITTORRENT_URL=http://192.168.1.71:8181
      - QBITTORRENT_USERNAME=tega
      - QBITTORRENT_PASSWORD=kdjdjkdkj

**Comment by ManiMatter** [comment]
pushed a fix to the "dev" image - can you pls pull and test?

**Comment by tegaologe** [comment]
here is the error 
tega@tega:/var/lib/casaos/apps/decluttarr$ docker logs decluttarr
[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]: 
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]: 
[INFO]: *** Current Settings ***
[INFO]: Version: dev
[INFO]: Commit: fb2af75
[INFO]: 
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]: 
[INFO]: Running every: 0 days 0 hours 10.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]: 
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.72:7878/api/v3
[INFO]: Sonarr: http://192.168.1.72:8989/api/v3
[INFO]: qBittorrent: http://192.168.1.72:8181/api/v2
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[ERROR]: !! Sonarr Error: !!
--- Logging error ---
TypeError: not enough arguments for format string
Call stack:
Message: 'Please update %s to at least version %s. Current version: %s'
Arguments: ('4.0.1.1131', '3.0.10.1567')
[WARNING]: At least one instance was not reachable. Waiting for 60 seconds, then exiting Decluttarr.

**Comment by ManiMatter** [comment]
argh. sorry for that. pushed another fix. hope we're good now.

**Comment by tegaologe** [comment]
it works now.. Thank you very much.

**Comment by ManiMatter** [comment]
Super thx for testing. Will merge to `latest` noe
