### ISSUE TITLE
WARNING]: >>> Queue cleaning failed on Radarr.

### ISSUE THREAD

**Issue by hmphok** [ManiMatter/decluttarr#128]
I'm getting this error, and for some reason the stalled DLs dont get removed.

[INFO]: ##################################################
[INFO]: Decluttarr - Application Started!
[INFO]:
[INFO]: Like this app? Thanks for giving it a ⭐️ on GitHub!
[INFO]: https://github.com/ManiMatter/decluttarr/
[INFO]:
[INFO]: *** Current Settings ***
[INFO]: Version: v1.46.1
[INFO]: Commit: c9ad596
[INFO]:
[INFO]: True | Removing failed downloads (REMOVE_FAILED)
[INFO]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
[INFO]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
[INFO]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
[INFO]: True | Removing orphan downloads (REMOVE_ORPHANS)
[INFO]: True | Removing slow downloads (REMOVE_SLOW)
[INFO]: True | Removing stalled downloads (REMOVE_STALLED)
[INFO]: True | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
[INFO]:
[INFO]: Running every: 0 days 0 hours 30.0 minutes
[INFO]: Minimum speed enforced: 100 KB/s
[INFO]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 3
[INFO]: Downloads with this tag will be skipped: "Don't Kill"
[INFO]: Private Trackers will be skipped: True
[INFO]:
[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.1.186:30025/api/v3
[INFO]: Radarr: http://192.168.1.186:30025/api/v3
[INFO]: qBittorrent: http://192.168.1.186:30024/api/v2
[INFO]:
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[INFO]: OK | Radarr
[INFO]: OK | qBittorrent
[INFO]:
[INFO]: ##################################################
[INFO]: LOG_LEVEL = INFO: Only logging changes (switch to VERBOSE for more info)
[INFO]: >>> Detected stalled download (1 out of 3 permitted times): Guardians of the Galaxy Vol 3 2023 2160p WEB-DL DDP5 1 Atmos HDR DV HEVC-CMRG
[INFO]: >>> Detected slow download (1 out of 3 permitted times): Killers.of.the.Flower.Moon.2023.2160p.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX[TGx]
[INFO]: >>> Detected slow download (1 out of 3 permitted times): Gladiator.2000.Extended.UHD.BluRay.2160p.DD.5.1.HDR.x265-BHDStudio
[INFO]: >>> Detected slow download (1 out of 3 permitted times): Five.Nights.at.Freddys.2023.4K.HDR.DV.2160p.BDRip Ita Eng x265-NAHOM
[INFO]: >>> Detected stalled download (2 out of 3 permitted times): Guardians of the Galaxy Vol 3 2023 2160p WEB-DL DDP5 1 Atmos HDR DV HEVC-CMRG
[WARNING]: >>> Queue cleaning failed on Radarr. (File: remove_unmonitored.py / Line: 18 / Error Message: 'episodeId' / Error Type: <class 'KeyError'>)

**Comment by hmphok** [comment]
I see that i have put the same IP for sonarr and radarr. I think it is working now.

**Comment by Cstegg** [comment]
same issue here

**Comment by ManiMatter** [comment]
> Queue cleaning failed on Radarr. (File: remove_unmonitored.py / Line: 18 / Error Message: 'episodeId' / Error Type: <class 'KeyError'>)

pretty self-explanatory.. why would radarr have a `episodeid`?!

```
[INFO](https://github.com/ManiMatter/decluttarr/issues/128##################################################): OK | Radarr
[INFO](https://github.com/ManiMatter/decluttarr/issues/128##################################################): OK | Radarr
```

Check your settings.. where you ought to provide the sonarr-ip, you provided the radarr one…

**Comment by Cstegg** [comment]
I get the same error but on the Whisparr instance

I ended up disabling the setting for removing unmonitored though which fixed it up for me

**Comment by hmphok** [comment]
> > Queue cleaning failed on Radarr. (File: remove_unmonitored.py / Line: 18 / Error Message: 'episodeId' / Error Type: <class 'KeyError'>)
> 
> pretty self-explanatory.. why would radarr have a `episodeid`?!
> 
> ```
> [INFO](https://github.com/ManiMatter/decluttarr/issues/128##################################################): OK | Radarr
> [INFO](https://github.com/ManiMatter/decluttarr/issues/128##################################################): OK | Radarr
> ```
> 
> Check your settings.. where you ought to provide the sonarr-ip, you provided the radarr one…

I changed the address and everything is fine now, sorry for wasting your time.

**Comment by ManiMatter** [comment]
I added in the latest version that checks this explicitly and hopefully gives back a more comprehensible message
