### ISSUE TITLE
Feature request regarding language support #92

### ISSUE THREAD

**Issue by volschin** [ManiMatter/decluttarr#129]
In the readme you describe the missing language support for languages other than english #92 .

You could provide environment variables for those messages you rely on in the program logic. If an environment variable is set, you take the string from there, if not you use the internal english one.

**Comment by ManiMatter** [comment]
Hi

you are right, that would be an option.
However if we go to that level of customizability, I fear at some point the config becomes to hard to understand (regardless whether the option is specified or not).

what I wonder though is whether there is an untranslated way to get these messages, ie all in english.

I see these avenues:
- hit qbit directly when available to get status from there (assuming we can get it in english)
- See if the status messages can be retrieved in english from sonarr (etc)
- See if we can use translation patterns from sonarr to translate


Likeliness: first one probably highest, others probably less.

**Comment by ManiMatter** [comment]
> Regarding the translations in qbt. https://github.com/qbittorrent/qBittorrent/tree/master/src/lang
> 
> Could be an option the user copies the needed ts itself and you read it if available.

Technically yes. For the average user I think that is too technical - personally I would prefer if it worked without user involvement

**Comment by ManiMatter** [comment]
Let‘s park this until https://github.com/Sonarr/Sonarr/issues/6960 is done

**Comment by ManiMatter** [comment]
Closed in favor of https://github.com/ManiMatter/decluttarr/issues/132
