### ISSUE TITLE
Detected stalled download, tagged not to be killed for every torrent

### ISSUE THREAD

**Issue by NeoDigi** [ManiMatter/decluttarr#13]
Hey,
so, so far I couldn't make this work ( I mean all the connection seems to be working but the container logs are like this:

```
[VERBOSE]: Cleaning queue on Radarr:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]: Cleaning queue on Sonarr:
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S03E10.The.Portrait.720p.AMZN.WEBRip.DDP5.1.x264-NTb
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S04.720p.AMZN.WEBRip.DDP5.1.x264-FLUX[rartv]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 27 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 31 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S03E08.The.Wellness.Center.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 24 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S05E06.Urgent.Care.720p.DSNP.WEB-DL.DDP5.1.H.264-NTb[TGx]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S05E05.Local.News.720p.DSNP.WEB-DL.DDP5.1.H.264-NTb[TGx]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 30 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What We Do in the Shadows S03E06 720p WEB H264 GGWP TGx
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Zero-Raws] One Piece - 05 (CX 1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Zero-Raws] One Piece - 06 (CX 1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 17 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Marine-ford] One Piece 15 - HD VOSTFR (1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S02E04.The.Curse.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb[eztv.io].mkv[eztv.li]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S02E02.Ghosts.720p.AMZN.WEBRip.DDP5.1.x264-NTb[eztv.io].mkv[eztv.li]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S05E07.Hybrid.Creatures.720p.DSNP.WEB-DL.DDP5.1.H.264-NTb[TGx]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.In.The.Shadows.S03E05.720p.WEB.h264-GOSSIP[eztv.re].mkv[eztv.li]
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: [Zero-Raws] One Piece - 03 (CX 1280x720 x264 AAC)
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S03E07.The.Siren.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rarbg]
[VERBOSE]: >>> Queue is clean.
```

so according to the log it seems like they are tag not to be killed even though they should 
On qBit When I filter the tag Dont kill if stalled, it returns that 0 torrent are actually tagged

Any clue on what Im doing wrong ?

**Comment by ManiMatter** [comment]
Hey, could you pls provide a screenshot of
- your sonarr queue where one of the affected series is visible
- your qbit where the same series are visible 
- your qbit tags

Im sure we'll figure it out, cheers!

**Comment by NeoDigi** [comment]
Yes one instance of qbit only

![Screenshot_20231203-080316.png](https://github.com/ManiMatter/decluttarr/assets/6572589/f85466d6-6254-4f23-a463-9399efe11ad6)

**Comment by ManiMatter** [comment]
Thx

Can you also share a your settings pls?

**Comment by ManiMatter** [comment]
I don't see anything completely wrong tbh. 

Does it change anything if you use 
NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill If Stalled

instead of 
NO_STALLED_REMOVAL_QBIT_TAG="Don't Kill If Stalled"

If not, we'll have to do some digging...

**Comment by NeoDigi** [comment]
I just tried this with the same results
I want to try to manually erase everything and start again from a clean state just to see if this changes anything

I'll report back after

**Comment by NeoDigi** [comment]
So I just tried with everything fresh and only one torrent and its still doing the same thing
```
[VERBOSE]: Cleaning queue on Radarr:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]: Cleaning queue on Sonarr:
[VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S05E06.Urgent.Care.720p.DSNP.WEB-DL.DDP5.1.H.264-NTb[TGx]
[VERBOSE]: >>> Queue is clean.
[VERBOSE]: 
[VERBOSE]: Queue clean-up complete!
[VERBOSE]: --------------------------------------------------
```
And this loops forever without ever removing this torrent :(

**Comment by iEusKid** [comment]
> So I just tried with everything fresh and only one torrent and its still doing the same thing
> 
> ```
> [VERBOSE]: Cleaning queue on Radarr:
> [VERBOSE]: >>> Queue is empty.
> [VERBOSE]: Cleaning queue on Sonarr:
> [VERBOSE]: >>> Detected stalled download, tagged not to be killed: What.We.Do.in.the.Shadows.S05E06.Urgent.Care.720p.DSNP.WEB-DL.DDP5.1.H.264-NTb[TGx]
> [VERBOSE]: >>> Queue is clean.
> [VERBOSE]: 
> [VERBOSE]: Queue clean-up complete!
> [VERBOSE]: --------------------------------------------------
> ```
> 
> And this loops forever without ever removing this torrent :(

I am not the developer but try to remove the part in compose file with tagged dont kill, try without it at all then see how it will do

**Comment by NeoDigi** [comment]
I just tried, no changes

**Comment by ManiMatter** [comment]
What's your qbit version?

**Comment by NeoDigi** [comment]
Yup, this was the issue
I was using qbit 4.3.9
and when I switched to 4.6.2 it started working without issues!

**Comment by ManiMatter** [comment]
Excellent glad we figured it out. Cheers
