### ISSUE TITLE
[Feature request] : Enable option for incorporating system time in logs when running in a Docker container

### ISSUE THREAD

**Issue by Nabstar3** [ManiMatter/decluttarr#130]
**Description:**

Currently, the application logs do not include timestamps when running inside a Docker container. However, for tracking 
important events and debugging, timestamps are beneficial and allow the user to ensure the application is executing actions in a time coordinated manner. It would be useful to enable timezone configuration based on the `TZ` (timezone) environment variable specified in the Dockerfile. This feature would allow the application to include appropriately time-stamped log messages reflecting the correct local time as configured in the container's environment.

**Proposed Solution:**

Modify the logging configuration to conditionally include timestamps in log messages when the `TZ` environment variable is set. This would allow users to have time-based logs reflecting the timezone specified in their Docker environment.

**Implementation Steps:**

1. **Check for `TZ` Environment Variable:**
   - During application startup, check if the `TZ` environment variable is set in the Docker container.
   
2. **Configure Logging Format:**
   - If the `TZ` variable is set, adjust the logging format to include timestamps.
   - Ensure the timestamps reflect the correct timezone as specified by `TZ`.

**Benefits:**

- Provides flexibility to include timestamps in logs when required.
- Ensures timestamps reflect the correct local time as per the configured timezone.
- Enhances the utility of logs for debugging and monitoring in environments where centralized logging is not used.

**Additional Notes:**

- Ensure compatibility with existing logging configurations.
- Test the implementation using the built in tests to ensure accuracy
---

By implementing this feature, users can benefit from time-stamped logs in Docker environments, improving the overall debugging and monitoring experience.

**Comment by ManiMatter** [comment]
I use dozzle to look at the logs - comes with timestamps even now.

If you feel this is still needed, would you like contributing with a PR?

**Comment by Nabstar3** [comment]
> I use dozzle to look at the logs - comes with timestamps even now.
> 
> If you feel this is still needed, would you like contributing with a PR?

Yes, I would like to contribute with a PR. This will be one of my few times that I have contributed to an open source repo and your patience and criticism is appreciated.

I wanted to know what the `verboselogger` module was for and how it's used?

**Comment by ManiMatter** [comment]
> > I use dozzle to look at the logs - comes with timestamps even now.
> > If you feel this is still needed, would you like contributing with a PR?
> 
> Yes, I would like to contribute with a PR. This will be one of my few times that I have contributed to an open source repo and your patience and criticism is appreciated.
> 
> I wanted to know what the `verboselogger` module was for and how it's used?

It has more log levels than the default logger (ie. The verbose-level)

**Comment by ManiMatter** [comment]
Btw - have you looked at dozzle? It may already give you what you need

**Comment by Nabstar3** [comment]
> Btw - have you looked at dozzle? It may already give you what you need (logs with timestamp)

I did after you suggested it, but I think a more native approach would greatly benefit users who don't wasn't to install an additional log handler.

**Comment by ManiMatter** [comment]
`docker-compose logs -t`
Does this show the timestamps natively (untested)?

Source: https://stackoverflow.com/a/38891293/1874025

**Comment by Nabstar3** [comment]
> `docker-compose logs -t` Does this show the timestamps natively (untested)?
> 
> Source: https://stackoverflow.com/a/38891293/1874025

This does work, yes.

However this applies to every container in the YAML, unless the user filters using `docker-compose logs -t | grep 'decluttarr'`

The output is such : `decluttarr     | 2024-07-18T01:55:51.251461504Z [INFO]: >>> Removing stalled download: Snowfall S02E10 720p WEBRip x264-TBS[ettv]` with a very ugly formatted datetime stamp.

**Comment by Nabstar3** [comment]
I believe I got it working when I run it manually using `main.py` and `config.conf` but I wanted to test using a docker build.

I'm trying to build it locally using the `Dockerfile` but I'm confused as to what these commands are for and why we're copying to the same directory ...

`COPY ./docker/requirements.txt ./docker/requirements.txt
RUN pip install --no-cache-dir -r docker/requirements.txt
COPY . .`

I've set the context of the build to ./docker as the dockerfile is contained within this directory but it fails when it tries to look for  `/docker/docker/requirements.txt`

**Comment by cascandaliato** [comment]
> However this applies to every container in the YAML, unless the user filters using `docker-compose logs -t | grep 'decluttarr'`

If you want logs of a single service then you can run `docker-compose logs -t decluttarr`.

**Comment by ManiMatter** [comment]
See reason for closure here:
https://github.com/ManiMatter/decluttarr/pull/133#issuecomment-2262873754
