### ISSUE TITLE
"Error making API request 404 Client Error: Not Found" when removing stalled downloads 

### ISSUE THREAD

**Issue by LMaier-dev** [ManiMatter/decluttarr#136]
Hi there,
I recently found this, thanks for the work, this was exactly what I needed!

Unfortunately there seems to be an issue with removing the stalled downloads:

```
[INFO]: >>> Removing missing metadata download: Eternal.Sunshine.Of.The.Spotless.Mind.2004.SWESUB.AC3.DVDRip.Xvi
[ERROR]: Error making API request to http://binhex-radarr:7878/api/v3/queue/206019644: 404 Client Error: Not Found for url: http://binhex-radarr:7878/radarr/api/v3/queue/206019644?removeFromClient=True&blocklist=True
```

I am not using the nightly release but the radarr version is 5.8.3.8933, which should be fine? I am using the binhex container which doesn't have nightly builds :(

I tried and could reach the radarr container from within decluttarr

Thanks again

**Comment by ManiMatter** [comment]
hi there,

Looks to me like a problem removing queue items generally and not specifically related to "missing metadata download" (and not "stalled", as you write).

Try the following:
- Go to your radarr instance
- Go to queue
- Open your developer-tab in your browser and go to network
- Clear the entries
- Now perform the actions as in the screenshot below:
1. Select the download
2. Click Remove 
3. Specify in the popup that you want to block list it, and that you want to search for a replacement
- Study the URL of the delete-request in your browser (and potentially copy it here)
.. my question: How is the delete request that you see in your browser different than the url that it could not find (as per your last post)?

<img width="903" alt="image" src="https://github.com/user-attachments/assets/e2829884-30a9-4568-a4b0-e83829470b9e">

**Comment by LMaier-dev** [comment]
Hi again,
Thanks for the quick response
Yeah it's not an issue with stalled downloads specifically, I just used it as a synonym (I didn't have a better name for it)

This is the URL that's used from the browser, does that help in any way?
```
http://<my-radarr-ip>:7878/radarr/api/v3/queue/206019644?removeFromClient=true&blocklist=false&skipRedownload=false&changeCategory=false
```
Except for the different parameters, the url seems to be the same though, given that it uses my server IP and not the container name.

The id is different because I manually removed it yesterday, hope that's not an issue? Also I used interactive search to select a torrent with only leechers, to test decluttarr.

**Comment by LMaier-dev** [comment]
To be sure I tried it with a stalled download and different movie as well.
From the logs:
´´´
[INFO]: >>> Detected stalled download too many times (4 out of 3 permitted times): American.Made.2017.1080p.BluRay.x264-GECKOS
[INFO]: >>> Removing stalled download: American.Made.2017.1080p.BluRay.x264-GECKOS
[ERROR]: Error making API request to http://binhex-radarr:7878/api/v3/queue/151907791: 404 Client Error: Not Found for url: http://binhex-radarr:7878/radarr/api/v3/queue/151907791?removeFromClient=True&blocklist=True
´´´

And when deleting it via browser:
```
DELETE http://10.98.1.2:7878/radarr/api/v3/queue/151907791?removeFromClient=true&blocklist=true&skipRedownload=false&changeCategory=false
´´´

**Comment by ManiMatter** [comment]
First impression: URL structure looks correct

clear difference: ip vs name of container.

my take: the name seems to work, else you would not even be getting to this point (eg all the get-requests seem to go through)

but the first post-call seems not to work

theories:
- your network blocks the post call between the containers
- What happens if you use ip in the settings rather than container name

**Comment by LMaier-dev** [comment]
unfortunately same issue when using the IP instead

**Comment by ManiMatter** [comment]
Could you please paste the URL that fails from the decluttarr logs and the one that works from your browser (with the exact same parameters) below so we see them side by side?

**Comment by LMaier-dev** [comment]
Okay I found the issue, I forgot to add the /radarr base to the url in the Env Variable:
```
[INFO]: >>> Removing missing metadata download: Eternal.Sunshine.Of.The.Spotless.Mind.2004.SWESUB.AC3.DVDRip.Xvi
[ERROR]: Error making API request to http://10.98.1.2:7878/api/v3/queue/206019644: 404 Client Error: Not Found for url: http://10.98.1.2:7878/radarr/api/v3/queue/206019644?removeFromClient=True&blocklist=True
```
You can see that the first url in the error message does not contain the base, while the second weirdly does? I'm also not sure why all the get requests worked fine?

But I just tried it and it did remove the missing metadata download directly, thanks again for this tool. This will really improve *arr by alot for me!

So you can close this, if you want

**Comment by ManiMatter** [comment]
Can you share what you had before and after?

**Comment by LMaier-dev** [comment]
Sure

Before:
http://binhex-radarr:7878
Now:
http://binhex-radarr:7878/radarr

**Comment by ManiMatter** [comment]
Thanks for sharing

No idea why it requires the `/radarr`
must be a particularity of your specific hex image
