### ISSUE TITLE
[Bug] Queue cleaning failure in v1.47.0

### ISSUE THREAD

**Issue by ReveredOxygen** [ManiMatter/decluttarr#138]
v1.47.0 does not function for me, as it just prints this error and never removes anything
```
[WARNING]: >>> Queue cleaning failed on Sonarr. (File: remove_failed_imports.py / Line: 39 / Error Message: local variable 'removal_messages' referenced before assignment / Error Type: <class 'UnboundLocalError'>)
```

Code analysis:
removal_messages is initialised inside an if statement, which may not always be executed. One potential fix would be to add `removal_messages = []` below line 15 of remove_failed_imports.py, to ensure it's always initialised.

**Comment by ManiMatter** [comment]
Thx for raising.

could you pls post the debug logs?

**Comment by ReveredOxygen** [comment]
Sure, see https://paste.gg/p/anonymous/c0f2fafaedb54c139fdd8cef47d78617

**Comment by ManiMatter** [comment]
Thanks for raising this bug and the logs.
It has been a while that I wanted to add some automated testing to increase the robustness.. Took this as a "motivator".

Added the tests, and also fixed the issue (including the one you added in your other issue).
Would you mind pulling the dev-image and verify?
