### ISSUE TITLE
Feature request: remove non-arr slow/stalled/errored from qbit (specific categories)

### ISSUE THREAD

**Issue by laleeroy** [ManiMatter/decluttarr#147]
It would be awesome if we could remove slow/stalled/errored downloads on non arr downloads by specificying which category decluttarr should look on qbittorrent

**Comment by ManiMatter** [comment]
Can you explain why you think that would be helpful please

**Comment by ManiMatter** [comment]
Not the goal of this app which focuses on *arr.

feel free to use the code and build your own script. Shouldn‘t be too hard.
