### ISSUE TITLE
Queue cleaning failed on Lidarr.

### ISSUE THREAD

**Issue by driesvandamme** [ManiMatter/decluttarr#15]
I get the following error output:
Queue cleaning failed on Lidarr. (File: queue_cleaner.py / Line: 233 / Error Message: 'downloadId' / Error Type: <class 'KeyError'>)

**Comment by spupuz** [comment]
i got the same error but for sonarr wath it is?

**Comment by ManiMatter** [comment]
Please open a new issue, and paste the log on verbose-mode to a pastebin
