### ISSUE TITLE
Docker Config file vs Variables

### ISSUE THREAD

**Issue by Healzangels** [ManiMatter/decluttarr#156]
Greetings! 

Wanted to say first off thanks for sharing just an awesome project!

Was wondering/hoping to find out. Is it possible with the Docker container method of installation to have a mapped config folder vs setting the variables. I'd love to be able to have a config file to setup/set the variables and values vs having to map those variables in docker compose file.

Or maybe this is already possible and I totally missed it!

Thanks again!

**Comment by ManiMatter** [comment]
Hi

No. Either you run it as script, and then you have a config. Or in docker, then you need to pass the docker params. Not planned to change

**Comment by mdcollins05** [comment]
@Healzangels You can force it to use a config file in Docker. The important bits to set are the environment variable `IS_IN_DOCKER` to an empty string (`''`) and to create the config file and mount just the file into the config directory. Here's a slimmed down `docker run` command:

```
docker run \
  --name='Decluttarr' \
  -e 'IS_IN_DOCKER'='' \
  -v '/mnt/cache/appdata/decluttarr/config.conf':'/app/config/config.conf':'rw' \
  'ghcr.io/manimatter/decluttarr:latest' 
```

@ManiMatter I propose that if the config file exists, read it in and use it. If any of the environment variables are set, let those values override the config file values. This allows for the flexibility to choose how to configure it.

**Comment by ManiMatter** [comment]
> @Healzangels You can force it to use a config file in Docker. The important bits to set are the environment variable `IS_IN_DOCKER` to an empty string (`''`) and to create the config file and mount just the file into the config directory. Here's a slimmed down `docker run` command:
> 
> ```
> docker run \
>   --name='Decluttarr' \
>   -e 'IS_IN_DOCKER'='' \
>   -v '/mnt/cache/appdata/decluttarr/config.conf':'/app/config/config.conf':'rw' \
>   'ghcr.io/manimatter/decluttarr:latest' 
> ```
> 
> @ManiMatter I propose that if the config file exists, read it in and use it. If any of the environment variables are set, let those values override the config file values. This allows for the flexibility to choose how to configure it.

Hi @mdcollins05 - thanks for supporting the other users! On your request: noz planning to add it myself due to time limits but happy to accept a PR if you would like to add it.

**Comment by ManiMatter** [comment]
@mdcollins05 @Healzangels - Just FYI, i added the possibility to use config files in docker setup in v2.
https://github.com/ManiMatter/decluttarr/tree/decluttarr-v2?tab=readme-ov-file#docker-docker-compose-together-with-configyaml


it's still a beta, but wanted to share in case you'd like to test

**Comment by Healzangels** [comment]
@mdcollins05 Thanks so much for the information and apologies that I'm only just now seeing your update, d'oh!  

@ManiMatter Thanks for the update as well! Very excited to give the config file method a try this weekend and will report back results/if I come across any issues. Thanks again, cheers!

**Comment by ManiMatter** [comment]
i'm pretty sure you'll find issues, so apprecaite any feedback or code contributions.
