### ISSUE TITLE
Error removing items

### ISSUE THREAD

**Issue by YourLastFate** [ManiMatter/decluttarr#157]
Decluttarr is able monitor shows, and recognize when they stall correctly.
It is only currently hooked up with sonarr and radarr, no other services.

Whenever it goes to remove a show from download, i get a bad url error.

```
[INFO]: >>> Removing stalled download: The Astronaut Wives Club S01E09 720p HDTV X264-DIMENSION[rartv]
[ERROR]: Error making API request to http://sonarr:8989/api/v3/queue/1256217565: 404 Client Error: Not Found for url: http://sonarr:8989/sonarr/api/v3/queue/1256217565?removeFromClient=True&blocklist=True
```

I am using a reverse proxy, nginx. 
Willing to provide any additional information that can assist.

**Comment by YourLastFate** [comment]
Current config file:

`decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000

      ## General
      # TEST_RUN=True
      # SSL_VERIFICATION=False
      LOG_LEVEL: INFO

      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: "True"
      REMOVE_FAILED_IMPORTS: "True"
      REMOVE_METADATA_MISSING: "True"
      REMOVE_MISSING_FILES: "True"
      REMOVE_ORPHANS: "True"
      REMOVE_SLOW: "True"
      REMOVE_STALLED: "True"
      REMOVE_UNMONITORED: "True"
      RUN_PERIODIC_RESCANS: |
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }

      ## Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      REMOVE_SLOW: "True"
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: |
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]

      ## Radarr
      RADARR_URL: http://radarr:7878
      RADARR_KEY: [REDACTED]

      ## Sonarr
      SONARR_URL: http://sonarr:8989
      SONARR_KEY: [REDACTED]

      ## Lidarr
      # LIDARR_URL: http://lidarr:8686
      # LIDARR_KEY: $LIDARR_API_KEY

      ## Readarr
      # READARR_URL: http://readarr:8787
      # READARR_KEY: $READARR_API_KEY

      ## Whisparr
      # WHISPARR_URL: http://whisparr:6969
      # WHISPARR_KEY: $WHISPARR_API_KEY

      ## qBitorrent
      # QBITTORRENT_URL: http://qbittorrent:8080
      # QBITTORRENT_USERNAME: 
      # QBITTORRENT_PASSWORD: 
    networks:
      - the_internet
      - media_mgmt_network
    depends_on:
      - swag`

Looking through [another message you have](https://github.com/ManiMatter/decluttarr/issues/92), i can see you included your local IP instead of radarr/sonarr, but when i change to 
`      SONARR_URL: http://192.168.68.200:8989`
the logs now show blank 
`No log line matching the '' filter`

**Comment by YourLastFate** [comment]
Current config file:

` decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000

      ## General
      # TEST_RUN=True
      # SSL_VERIFICATION=False
      LOG_LEVEL: INFO

      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: "True"
      REMOVE_FAILED_IMPORTS: "True"
      REMOVE_METADATA_MISSING: "True"
      REMOVE_MISSING_FILES: "True"
      REMOVE_ORPHANS: "True"
      REMOVE_SLOW: "True"
      REMOVE_STALLED: "True"
      REMOVE_UNMONITORED: "True"
      RUN_PERIODIC_RESCANS: |
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }

      ## Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      REMOVE_SLOW: "True"
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: |
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]

      ## Radarr
      RADARR_URL: http://radarr:7878
      RADARR_KEY: [REDACTED]

      ## Sonarr
      SONARR_URL: http://sonarr:8989
      SONARR_KEY: [REDACTED]

      ## Lidarr
      # LIDARR_URL: http://lidarr:8686
      # LIDARR_KEY: $LIDARR_API_KEY

      ## Readarr
      # READARR_URL: http://readarr:8787
      # READARR_KEY: $READARR_API_KEY

      ## Whisparr
      # WHISPARR_URL: http://whisparr:6969
      # WHISPARR_KEY: $WHISPARR_API_KEY

      ## qBitorrent
      # QBITTORRENT_URL: http://qbittorrent:8080
      # QBITTORRENT_USERNAME: 
      # QBITTORRENT_PASSWORD: 
    networks:
      - the_internet
      - media_mgmt_network
    depends_on:
      - swag`

Looking through [another message](https://github.com/ManiMatter/decluttarr/issues/92), i can see the IP address is included instead of radarr/sonarr, but when i change to 
`      SONARR_URL: http://192.168.x.x:8989`
the logs now show blank 
`No log line matching the '' filter`

**Comment by ManiMatter** [comment]
`http://sonarr:8989` works only if "sonarr" in resolves to the IP of your sonarr-container. 
Works for instance well on bridge-networks of traefik reverse-proxy (that's what I use).

Regardless what proxy you use, you need to make sure that decluttarr and your other arr apps are in the same network so that they can communicate to each other.


If that doesn't help - please provide the full log

**Comment by YourLastFate** [comment]
All *arr services are on network: media_mgmt_network

[INFO]: *** Configured Instances ***
[INFO]: Radarr: http://radarr:7878
[INFO]: Sonarr: http://sonarr:8989
[INFO]: *** Check Instances *** 
[DEBUG]: Starting new HTTP connection (1): radarr:7878
[DEBUG]: http://radarr:7878 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://radarr:7878 "GET /radarr/api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): radarr:7878
[DEBUG]: http://radarr:7878 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://radarr:7878 "GET /radarr/api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): radarr:7878
[DEBUG]: http://radarr:7878 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://radarr:7878 "GET /radarr/api/v3/system/status HTTP/11" 200 None
[INFO]: OK | Radarr
[DEBUG]: Current version of RADARR: 5.11.0.9244
[INFO]: 
[DEBUG]: Starting new HTTP connection (1): sonarr:8989
[DEBUG]: http://sonarr:8989 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): sonarr:8989
[DEBUG]: http://sonarr:8989 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/system/status HTTP/11" 200 None
[DEBUG]: Starting new HTTP connection (1): sonarr:8989
[DEBUG]: http://sonarr:8989 "GET /api/v3/system/status HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/system/status HTTP/11" 200 None
[INFO]: OK | Sonarr
[DEBUG]: Current version of SONARR: 4.0.9.2244

------------

[DEBUG]: http://sonarr:8989 "GET /api/v3/queue HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/queue HTTP/11" 200 None
[DEBUG]: http://sonarr:8989 "GET /api/v3/queue?page=1&pageSize=202 HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/queue?page=1&pageSize=202 HTTP/11" 200 None
[DEBUG]: http://sonarr:8989 "DELETE /api/v3/queue/1485829804?removeFromClient=True&blocklist=True HTTP/11" 302 0
[DEBUG]: http://sonarr:8989 "GET /sonarr/api/v3/queue/1485829804?removeFromClient=True&blocklist=True HTTP/11" 404 0
[ERROR]: Error making API request to http://sonarr:8989/api/v3/queue/1485829804: 404 Client Error: Not Found for url: http://sonarr:8989/sonarr/api/v3/queue/1485829804?removeFromClient=True&blocklist=True

[_decluttarr_logs(1).txt](https://github.com/user-attachments/files/17269755/_decluttarr_logs.1.txt)
[_decluttarr_logs(2).txt](https://github.com/user-attachments/files/17269757/_decluttarr_logs.2.txt)

*I cant get the formatting to fight nicely with me...

**Comment by ManiMatter** [comment]
just to ask the obvious:
-> did you follow the readme from "stable" or "dev"?
Latest points to "stable"

-> are you using any special radarr/sonarr or the official one?
e.g., `lscr.io/linuxserver/radarr:nightly`


PS: I am just fighting (today) with a update to the stable - maybe wait till the new package is out, will let you know here. maybe your problem then goes away

**Comment by YourLastFate** [comment]
One of my first troubleshooting steps was to change the image i pulled from, to the one listed on their respective sites

`  radarr:
    image: lscr.io/linuxserver/radarr:latest
    #image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/USER/docker/radarr:/config
      - /home/USER/Media/Movies:/movies
      - /home/USER/Media/downloads:/downloads
      - nfs-movies:/movies-NAS
      - nfs-anime:/anime-NAS
    #ports:
      #- 7878:7878
    restart: always
    networks:
      - media_mgmt_network
      - the_internet
    depends_on:
       - swag
       - prowlarr
       - qbittorrent

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    #image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/USER/docker/sonarr:/config
      - /home/USER/Media/TV:/tv
      - /home/USER/Media/downloads:/downloads
      - nfs-tv:/tv-NAS
      - nfs-anime:/anime-NAS
    #ports:
      #- 8989:8989
    restart: always
    networks:
      - media_mgmt_network
      - the_internet
    depends_on:
       - swag
       - prowlarr
       - qbittorrent`

I appreciate your help. Its odd to me that it can see everything, but when it goes to update it, it gets a bad URL error.

Im noting that it seems to make multiple pulls before it gets a version number. Is this normal behavior?

**Comment by ManiMatter** [comment]
Just released a new version.
Could you please pull that one, and let's see if by coincidence your problem goes away. 
If not, let's take it from there, would appreciate a new set of logs based on that latest version.

**Comment by YourLastFate** [comment]
[_decluttarr_logs(5).txt](https://github.com/user-attachments/files/17270301/_decluttarr_logs.5.txt)

**Comment by YourLastFate** [comment]
From decluttarr

`2024-10-06T21:07:31.799780162Z [DEBUG]: http://172.19.0.15:8989 "DELETE /api/v3/queue/1221532036?removeFromClient=True&blocklist=True HTTP/11" 302 0

2024-10-06T21:07:31.800987522Z [DEBUG]: http://172.19.0.15:8989 "GET /sonarr/api/v3/queue/1221532036?removeFromClient=True&blocklist=True HTTP/11" 404 0

2024-10-06T21:07:31.801206499Z [ERROR]: Error making API request to http://172.19.0.15:8989/api/v3/queue/1221532036: 404 Client Error: Not Found for url: http://172.19.0.15:8989/sonarr/api/v3/queue/1221532036?removeFromClient=True&blocklist=True`

------------

From sonarr

`2024-10-06 17:07:31.7|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.

2024-10-06 17:07:31.7|Debug|Sonarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.

2024-10-06 17:07:31.7|Debug|Api|[DELETE] /api/v3/queue/1221532036?removeFromClient=True&blocklist=True: 302.Redirect (0 ms)`

------------

Lots more, can send the full logs if you like, but it is basically the same for all of them

**Comment by ManiMatter** [comment]
First of all, kudos for the granularity of logs you provide! Looks like you know what you're doing :)

Hard to tell what's going on here.
I think the good news is that the Sonarr logs suggest that it receives the calls from Decluttarr. So we can rule out (I think) a network configuration issue with your reverse proxy.

I think we need to to a bit of probing. Would you be so kind and do the following:
1) Look in your logs for one queue item that has that problem (e.g, delete queue that fails)
2) Go to your radarr or sonarr instance, and find that item on your queue
3) In your browser, open the network tab (F12 usually)
4) Clear + Start recording the network traffic
5) Manually delete the item, with the options remove from download client and block listing it

I am curious to see 
a) Whehter it works when you do it manually
b) Compare the URL etc against the URL from the logs

**Comment by YourLastFate** [comment]
I will look into this tomorrow night for certain.
Im running Linux Mint FWIW.

Glad I could give you good logs! 😄

I have in no way configured the proxy for declutter, I may have missed any notation if one exists, but the fact that it can see all the requests suggests to me that it should be working.

My money is on either sonarr not understanding the request, or the 302 redirect tag at the end (though idk what that would mean)

Time now is 00:52, I will aim to have new information for you around 23:00.

**Comment by ManiMatter** [comment]
you're overdue ;-)

just kidding. whenver you have a chance. Cheers

**Comment by YourLastFate** [comment]
Haha, not very good at following through, am I?
Still waiting for power to come back from the storm.
Once it’s back and I can get my house back in whatever can be defined as order, I will get that for you

thank you for your patience!!

**Comment by YourLastFate** [comment]
Please find attached a full networking log, a screenshot, and some highlights, for the sake of being thorough.

[192.168.68.200_Archive [24-10-20 20-21-37].txt](https://github.com/user-attachments/files/17452648/192.168.68.200_Archive.24-10-20.20-21-37.txt)
![Screenshot from 2024-10-20 20-30-22](https://github.com/user-attachments/assets/05702a5c-3c68-4b79-940c-0470f21449bd)

Network Logs have the URL as:
`https://192.168.68.200/sonarr/api/v3/queue/581629149?removeFromClient=true&blocklist=true&skipRedownload=true&changeCategory=false`

Decluttarr has the URL as:
`http://172.19.0.15:8989/sonarr/api/v3/queue/1221532036?removeFromClient=True&blocklist=True`

There are extra parameters at the end of the networks URL, but also the network has "True" in all lowercase.

I do like the telling it to search again immediately, with "skipRedownload=false":
`https://192.168.68.200/sonarr/api/v3/queue/475082696?removeFromClient=true&blocklist=true&skipRedownload=false&changeCategory=false`

**Comment by ManiMatter** [comment]
Glad to see you back, hope your house is still somewhat standing!

I just tested it out and the boolean value should be case agnostic, so don't think `True` vs `true` makes the difference.
`skipRedownload=false` does not need to be added, since it's the default (see [here](https://sonarr.tv/docs/api/#/Queue/delete_api_v3_queue__id_))

Going back to your initial logs, and comparing it with your last screenshot, the big difference is the status code 200 (screenshot) and 302 (logs).

> 2024-10-06 17:07:31.7|Debug|Api|[DELETE] /api/v3/queue/1221532036?removeFromClient=True&blocklist=True: 302.Redirect (0 ms)`

I am a bit blind in what happens here. Could you maybe ask the question in the sonarr discord channel, and check with them what **302.Redirect (0 ms)** means? I would do it for you, but if they then have questions that relate to your specific setup, I wouldn't be able to answer, so best for you to ask directly.

Looking forward to hearing from you what you find out.

Btw - one more ask: Under Settings/General you can set the logs to "Trace".
What do you get on that level? Any more details that could help us?

**Comment by ManiMatter** [comment]
Any news?

**Comment by ManiMatter** [comment]
Closing assuming resolved
