### ISSUE TITLE
BUG: Downloads with missing metadata are not being detected in qBittorrent v5

### ISSUE THREAD

**Issue by codersaur** [ManiMatter/decluttarr#168]
I've a number of downloads stuck in state "Downloanding Metadata" in qBittorrent v5. I have the REMOVE_METADATA_MISSING set to True, but they are still not being detected.

**Comment by ManiMatter** [comment]
Can you pls post debug logs?

**Comment by codersaur** [comment]
Having looked into this a bit more, it seems the issue is that the arr app (in this case whisparr) does not report the same status as qBittorrent. In whisparr the downloads have a status of "Downloading", whereas in qBittorrent their status is "[F] Downloading metadata" (or "state": "forcedMetaDL" in the json output from /api/v2/torrents/info). They are stuck like this for over a week. 

I feel the solution would be to identify downloads with state="forcedMetaDL" or "MetaDL" directly from the qBittorrent API.

**Comment by ManiMatter** [comment]
https://github.com/Sonarr/Sonarr/blob/86446a768627b98909389eac230720fcd00cb127/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L286-L287

I don't want to re-engineer the normalization that the arr apps so beautifully do to derive the different torrent statuses.
However, from what you desscribe, I think it's probably a very easy fix on whisparr.

Consider the above snipped from sonarr.
If you find the same code in whisparr - maybe you can even suggest a PR yourself?

Cheers

**Comment by codersaur** [comment]
Looks like whisparr does need a fix to treat a qbittorrent state="forcedMetaDL" the same as "MetaDL".

However, I don't think this will solve my issue. It seems all the arr apps use similar logic to convert a qbittorrent state="MetaDL|forcedMetaDL" to an item.Status = DownloadItemStatus.Queued. So said downloads are just reported the same as all other queued downloads, meaning we can't distinguish the ones that have been stuck downloading metadata for a long time (which I want to purge) vs the ones that have just been queued for a long time (which I wouldn't want to purge). 

The solution is either going to be to get all the arr apps to distingush the status and have a new DownloadItemStatus (for example "DownloadItemStatus.GettingMetaData"), which I think might be an uphill battle, OR to have decluttarr go directly to qbittorrent to identify them. wdyt?

**Comment by ManiMatter** [comment]
Dont worry about the queue distinction; I can do it via the message they post.

if you help getting whisparr fixed like sonarr, it‘ll work

**Comment by codersaur** [comment]
I've raised a bug report for Whisparr, but I'm not hopeful it'll get implemented any time soon, There haven't been any updates in the last six months...

**Comment by ManiMatter** [comment]
Try implementing it yourself. Its not difficult ;-)
Just move the lines in the code..

**Comment by codersaur** [comment]
I'm using the hotio/whisparr container image, and the issue is in the compiled .cs code. I'm not sure of the best approach to make the code edit and actually get it running on my machine. Any ideas?

**Comment by ManiMatter** [comment]
Fork the git; 
Edit in your own git
Build in vs code to test
Push your change
Pull request.

check the howto from the arr-apps, where they explain it
