### ISSUE TITLE
Queue cleaning failed on Sonarr

### ISSUE THREAD

**Issue by markhaines** [ManiMatter/decluttarr#172]
Seeing the following error in the log files:

[WARNING]: >>> Queue cleaning failed on Sonarr. (File: run_periodic_rescans.py / Line: 99 / Error Message: 'airDate' / Error Type: 
<class 'KeyError'>)

Not sure how to troubleshoot the issue further?

**Comment by ManiMatter** [comment]
Hey Mark. 
Interesting - maybe the "airDate" is an optional field that Sonarr does not provide if not filled.

Let me quickly do a fix - would you mind testing?

**Comment by markhaines** [comment]
Yes of course!

**Comment by ManiMatter** [comment]
image "fix-no-airDate" - currently building, should be ready for you to pull in 1-2min

**Comment by markhaines** [comment]
Have upgraded to it - will report back!

**Comment by ManiMatter** [comment]
Does it work? If yes, will merge to latest image

**Comment by markhaines** [comment]
> Does it work? If yes, will merge to latest image

Hi, sorry for delay - yes I tho k it's working perfectly now, thanks!
