### ISSUE TITLE
docker compose has formatting error

### ISSUE THREAD

**Issue by t288matt** [ManiMatter/decluttarr#174]
I can't get the docker compose yaml in the README to run in docker.
I've also tried numerous yaml linters and it fails, but.... I can't figure out why.

Maybe someone more experienced than me might be able to fix

**Comment by ManiMatter** [comment]
I would need a bit of more details to be able to help you out pls.

What error are you getting?
What OS are you on?
There are several git-issues on decluttarr git that contain yaml alternatives - did you check if one of these work for you?

**Comment by t288matt** [comment]
![image](https://github.com/user-attachments/assets/3d2b3ad9-dbdf-418d-8994-be4b6f7a6286)
 is the error I get on a ubuntu VM on proxmox.
 
 I've run the yaml from the README through several yaml validators such as yamllint.com and yamlchecker.com and they all show yaml syntax errors. 
![image](https://github.com/user-attachments/assets/e3b6f151-4d66-4952-bbcd-bd91eb6a31b5)
 Unfortunately i'm not skilled enough to know whats wrong

**Comment by t288matt** [comment]
but I''ve found one from the Issues that works. thanks.

**Comment by ManiMatter** [comment]
Very simple: yaml is a very picky format. Bad indentation means you have too little or too many spaces. 

Can happen when you copy from a website that it removes spaces…

Btw: try chatgpt to understand such issues
