### ISSUE TITLE
Queue cleaning failed on formattedQueueInfo

### ISSUE THREAD

**Issue by ookla-ariel-ride** [ManiMatter/decluttarr#180]
I am seeing this error when processing the Lidarr queue:

2024-10-27 08:15:28,312 [WARNING]: >>> Queue cleaning failed on formattedQueueInfo. (File: shared.py / Line: 335 / Error Message: 'downloadId' / Error Type: <class 'KeyError'>)

**Comment by ManiMatter** [comment]
Thx

could you pls share debug-level logs?
Pls only disable sonarr/radarr and all jobs that dont cause an error

**Comment by ookla-ariel-ride** [comment]
attached is the output with Debug enabled and just the orphan download removal enabled.
[decluttar.txt](https://github.com/user-attachments/files/17535403/decluttar.txt)

**Comment by ManiMatter** [comment]
Can you please pull [fix-lidarr-error-details](https://github.com/users/ManiMatter/packages/container/decluttarr/295923414?tag=fix-lidarr-error-details) and post the logs again? I added more logs to this version, so hopefully we find out what causes it.

**Comment by ookla-ariel-ride** [comment]
ok, I ran with the patch.  the output doesn't look too different. 
[ducluttarr_w_patch.txt](https://github.com/user-attachments/files/17535797/ducluttarr_w_patch.txt)

**Comment by ManiMatter** [comment]
i can't tell which version you ran since you execute locally.
are you sure you pulled the right branch (fix-lidarr-error-details)

**Comment by ookla-ariel-ride** [comment]
I verified the change is in place. Only a single file is changed in the code.  You can see the additional verbiage you added to the log output, however that change didn't add any new information.

Also, I am seeing this same error occur with Radarr and Sonarr as well, so it isn't just Lidarr.  Wondering if there are illegal characters in JSON that are causing parsing errors or something like that.

**Comment by ManiMatter** [comment]
> ok, I ran with the patch. the output doesn't look too different. [ducluttarr_w_patch.txt](https://github.com/user-attachments/files/17535797/ducluttarr_w_patch.txt)


I don't think you are using the right version
Your logs read:

> 2024-10-27 16:03:55,964 [WARNING]: >>> Queue cleaning failed on formattedQueueInfo. (File: shared.py / Line: 335 / Error Message: 'downloadId' / Error Type: <class 'KeyError'>)
> 2024-10-27 16:03:55,964 [DEBUG]: KeyError: 'downloadId'

and in the version I had pushed for you i had changed the format of that message:

https://github.com/ManiMatter/decluttarr/blob/e675469b0351bdc6e432944f5d5868c0ef6b93ae/src/utils/shared.py#L316-L322

Based on above code, the message should look like this (example):

> 2024-10-27 16:03:55,964 [WARNING]: >>> Queue cleaning failed on formattedQueueInfo. (File: shared.py / Line: 335 / KeyError: 'downloadId')

Given you still show the old message, my take is that you are not running the new code, which would have more logs:
https://github.com/ManiMatter/decluttarr/blob/e675469b0351bdc6e432944f5d5868c0ef6b93ae/src/utils/shared.py#L354-L355

**Comment by ookla-ariel-ride** [comment]
[Uploading decluttarr_w_debug_rev2.txt…]()
ok, I fixed the issue on my end.  The log now shows the proper output.  

I now see this in the output:

> 2024-10-28 13:56:06,789 [DEBUG]: formattedQueueInfo/queue_item with error for debug: {'artistId': 1552, 'albumId': 76994, 'quality': {'quality': {'id': 6, 'name': 'FLAC'}, 'revision': {'version': 1, 'real': 0, 'isRepack': False}}, 'customFormats': [], 'customFormatScore': 0, 'size': 616811400, 'title': 'Grateful Dead Road Trips Vol 3 No 1 CD2 - "10-One More Saturday Night.flac"', 'sizeleft': 616811400, 'timeleft': '00:00:31.0556128', 'estimatedCompletionTime': '2024-10-28T20:56:37Z', 'added': '2024-10-23T00:42:35Z', 'status': 'downloadClientUnavailable', 'protocol': 'usenet', 'downloadClientHasPostImportCategory': False, 'indexer': 'DrunkenSlug (Prowlarr)', 'trackFileCount': 2, 'trackHasFileCount': 0, 'downloadForced': False, 'id': 2106459866}
2024-10-28 13:56:06,790 [DEBUG]: remove_orphans/full queue IN: error
2024-10-28 13:56:06,823 [WARNING]: >>> Queue cleaning failed on formattedQueueInfo. (File: shared.py / Line: 333 / KeyError: 'downloadId'

**Comment by ManiMatter** [comment]
Thank you.

I am not sure I understand why "downloadId" is not contained in that queue item.

Can you share a screenshot from lidarr where we see this item?
Do you have any clue why it doesn't have the downloadId?

Maybe this is a clue:

> 'status': 'downloadClientUnavailable'

**Comment by ookla-ariel-ride** [comment]
This part doesn't look right with the double quotes.  It seems Lidarr has parsed something incorrectly.

>  'title': 'Grateful Dead Road Trips Vol 3 No 1 CD2 - "10-One More Saturday Night.flac"'

**Comment by ManiMatter** [comment]
Not sure the double quotes matter. Encapsualting double quotes in single quotes looks OK to me.

Would you be able to share screenshot of lidarr and any hunches why it says downloadClientUnavailable/any other hunch what's going on?

**Comment by ookla-ariel-ride** [comment]
ok, I have no idea why I had 2 downloads that were erroring with that downloadClientUnavailable entry.  I removed both of them from sonarr GUI and now the script is running clean again.

Thsi makes sense that this would be an exception, since this code is designed to remove downloads from the download client.  If it doesn't exist or is unavailable then that is a problem.

**Comment by ManiMatter** [comment]
Asking again; what does downloadClientUnavailable  mean? Is your client offline? Should this be removed? Do they potentially selfheal? Its not clear to me what causes this situation in the first place, thus hard for me to prescribe a remedy

**Comment by ookla-ariel-ride** [comment]
the download client is not offline.  I just had 2 entries with this value set.  I deleted them and now the script runs clean again. I hafe no idea why downloadCLientUnavailable is set, as I only have a single download client and it is not unavailable.

Maybe the script can be configured to remove these entires if found instead of erroring out.

**Comment by ManiMatter** [comment]
If we dont know what causes them I dont want to autoremove

we can look into it if it reoccurs
