### ISSUE TITLE
Cannot Create from YAML File

### ISSUE THREAD

**Issue by MGBeadz** [ManiMatter/decluttarr#182]
I'm having an issue where when running `docker-compose up -d` on the YML file I get the following error 

yaml: line 3: did not find expected key

This is the first application I'm installing with Docker Compose as well as being new to Docker in general, so not sure if I'm doing something wrong but as far as I can tell I changed the YML properly.

**Comment by bryancowell** [comment]
I had to rewrite it.  still having an issue translating this:
      - RUN_PERIODIC_RESCANS=[
          {
           "SONARR":[{"MISSING":true, "CUTOFF_UNMET":true, "MAX_CONCURRENT_SCANS":3, "MIN_DAYS_BEFORE_RESCAN":7}],
            "RADARR":[{"MISSING":true, "CUTOFF_UNMET":true, "MAX_CONCURRENT_SCANS":3, "MIN_DAYS_BEFORE_RESCAN":7}]
          }

try this to start:

  decluttarr:
    container_name: decluttarr
    image: ghcr.io/manimatter/decluttarr:latest
    restart: always
    environment:
      - PUID=xxx
      - PGID=xxx
      - UMASK=xxx
      - TZ=${TIMEZONE:?err}
     ## General
     # - TEST_RUN=False
     # SSL_VERIFICATION=False
      - LOG_LEVEL=VERBOSE
     ## Features 
      - REMOVE_TIMER=30
      - REMOVE_FAILED=True
      - REMOVE_FAILED_IMPORTS=True
      - REMOVE_METADATA_MISSING=True
      - REMOVE_MISSING_FILES=True
      - REMOVE_ORPHANS=True
      - REMOVE_SLOW=True
      - REMOVE_STALLED=True
      - REMOVE_UNMONITORED=True
      - RUN_PERIODIC_RESCANS=[
          {
            "SONARR":[{"MISSING":true, "CUTOFF_UNMET":true, "MAX_CONCURRENT_SCANS":3, "MIN_DAYS_BEFORE_RESCAN":7}],
            "RADARR":[{"MISSING":true, "CUTOFF_UNMET":true, "MAX_CONCURRENT_SCANS":3, "MIN_DAYS_BEFORE_RESCAN":7}]
          }
     # Feature Settings
      - PERMITTED_ATTEMPTS=3
      - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
      - REMOVE_SLOW=True
      - MIN_DOWNLOAD_SPEED=100     
      - FAILED_IMPORT_MESSAGE_PATTERNS=["Not a Custom Format upgrade for existing","Not an upgrade for existing"]
     ## Radarr
      - RADARR_URL=http://radarr:7878
      - RADARR_KEY=${RADARR_API_KEY:?err}
     ## Sonarr
      - SONARR_URL=http://sonarr:8989
      - SONARR_KEY=${SONARR_API_KEY:?err}
     ## Lidarr
      - LIDARR_URL=http://lidarr:8686
      - LIDARR_KEY=${LIDARR_API_KEY:?err}
     ## Readarr
      - READARR_URL=http://readarr:8787
      - READARR_KEY=${READARR_API_KEY:?err}

**Comment by bryancowell** [comment]
check the closed issues for a dockge working example

**Comment by MGBeadz** [comment]
> check the closed issues for a dockge working example

Ahh, I now see I'm not the only one who was running into that. Thanks!

**Comment by ManiMatter** [comment]
Thank you both. I've referenced this ticket from the ReadMe and also added the above code snippet into the readme to help future users. 

**@Anyone:** Please feel free to add to this issue more examples of docker-composes that work for you that may help others

**Comment by ManiMatter** [comment]
Thank you all, it's so great to see users help each other.

I added a link to https://github.com/ManiMatter/decluttarr/issues/173 in the ReadMe, so we can start collecting docker-compose examples over there. Would be great if you made a start and share above example in that thread (unless the code of that issue already covers it)

**Comment by CBerrIT** [comment]
This yml works for me.
https://pastebin.com/3dBcpw9H

**Comment by MGBeadz** [comment]
> This yml works for me. https://pastebin.com/3dBcpw9H

Hmm, interesting. Your version was the only one I've been able to get to "compose" from command line, but once it's created then I'm getting the following error

`The value retrieved for [features]: RUN_PERIODIC_RESCANS is "{`

It's wacky that it's so hit or miss for this many people.
