### ISSUE TITLE
Add to Unraid Community Apps

### ISSUE THREAD

**Issue by kristianbinau** [ManiMatter/decluttarr#183]
Hi,
It would be really cool if you could add this to the [Unraid Community Apps](https://unraid.net/community/apps). : )

**Comment by ManiMatter** [comment]
hi @kristianbinau , thanks for the suggestion. I am not familiar with Unraid Community Apps.

Can you tell me more what the advantage would be of adding it there and what what would take?

**Comment by kristianbinau** [comment]
Hi,

Not sure how easy it actually is, there's a few guides: https://forums.unraid.net/topic/57181-docker-faq/#comment-566084  
And also some policies: https://forums.unraid.net/topic/87144-ca-application-policies-notes/  

The advantages would be that you open the app up to a lot of users, that can easily install your app.
Unraid is NAS software, that also usually hosts a lot of docker containers, plex, sonarr, radarr, etc.

It's totally alright if you don't care to set it up : )

**Comment by ManiMatter** [comment]
Just checked out [instructions](https://forums.unraid.net/topic/57181-docker-faq/#comment-566084) and corresponding [video](https://www.youtube.com/watch?v=g6iMwea-HLY&t=15s&ab_channel=IBRACORP)

The first bullet in the instructions say:
> On the Settings tab, docker, select Docker Authoring Mode (The docker service has to be stopped to do this)

Unfortunately, it seems that I need a proper instance of Unraid to get this added, which I don't have.
Can you set it up yourself and publish it?

I think you can link to this github repo still...

or any other pointers how I can set it up myself?

**Comment by kristianbinau** [comment]
Yeah, it does look like that... I'll try to give it a try next time I have time : )

**Comment by ManiMatter** [comment]
will close for now since no action on my side - hope thats fine with you
