### ISSUE TITLE
Decluttarr searching for unmonitored seasons

### ISSUE THREAD

**Issue by so7ow** [ManiMatter/decluttarr#185]
On shows that are monitored by Sonarr, but have some seasons unmonitored, decluttarr is triggering a search/download for those unmonitored seasons' episodes. How can I prevent this undesirable behavior?

**Comment by ManiMatter** [comment]
Could you provide an example/screenshots of what you are observing?

**Comment by so7ow** [comment]
Sure, I'll upload screenshots in a moment, but an example is The Challenge. I have the show monitored, but I only have seasons 1, 39 & 40 monitored; decluttarr is triggering searches for episodes in season 5.

**Comment by so7ow** [comment]
Series monitored:
[decluttarr 1](https://github.com/user-attachments/assets/4ff615dd-9fe7-4a4f-bfc0-ad34cc0d66b2)

Season 5 not monitored:
![decluttarr 2](https://github.com/user-attachments/assets/cb493ce4-6b82-4c4f-bdea-ca059ec6480a)

decluttar searching for season 5 episodes:
![decluttarr 3](https://github.com/user-attachments/assets/9ffb1d4f-4f44-4746-bba3-992a5c53967a)


Anything else I can provide, @ManiMatter ?

**Comment by so7ow** [comment]
Ack, as I was looking at those screenshots, I realized I somehow have the individual episodes monitored! I'll go undo that.

**Comment by so7ow** [comment]
Closing. My bad!
