### ISSUE TITLE
Incorrect "git clone" command in the readme

### ISSUE THREAD

**Issue by saladm2** [ManiMatter/decluttarr#189]
Hi,

Thanks for this great app! There was a user on reddit experiencing an issue downloading the repo to install it so I just wanted to bring this to your attention.

In the readme under Getting Started --> Method 2, step 1 says

"Clone the repository with `git clone -b main https://github.com/ManiMatter/decluttarr.git`"

But this command fails because there is no branch named `main`. It's called `dev`.

So the command should be `git clone -b dev https://github.com/ManiMatter/decluttarr.git` or just `git clone https://github.com/ManiMatter/decluttarr.git`

**Comment by ManiMatter** [comment]
Thanks for flagging this. Updated the readme.
