### ISSUE TITLE
Allow optional use of tag protection feature

### ISSUE THREAD

**Issue by kstanleyadams** [ManiMatter/decluttarr#190]
[This client](https://github.com/rogerfar/rdt-client) replicates the qBittorrent API, but it does not implement the tag feature.

The endpoints /api/v2/torrents/tags and /api/v2/torrents/createTags are not implemented.

This makes decluttarr incompatible with rdt.

Would you consider making the usage of NO_STALLED_REMOVAL_QBIT_TAG tag protection optional?

> [INFO]: *** Configured Instances ***
[INFO]: Radarr: http://192.168.0.10:7878
[INFO]: Sonarr: http://192.168.0.10:8989
[INFO]: qBittorrent: http://192.168.0.10:6500
[INFO]: 
[INFO]: *** Check Instances ***
[INFO]: OK | Radarr
[INFO]: OK | Sonarr
[INFO]: OK | qBittorrent
[INFO]: 
HTTP Error: 404 Client Error: Not Found for url: http://192.168.0.10:6500/api/v2/torrents/tags
TypeError: argument of type 'NoneType' is not iterable

**Comment by ManiMatter** [comment]
Just dont specify qbit URL.
That should do the trick

ps: you are the 2nd person to flag this. Maybe do you want to raise with Rdt team that they add tag feature over there?

**Comment by kstanleyadams** [comment]
If I don’t specify the url, then your tool will not be able to remove the failed downloads from rdt if I understand correctly. Or are you using sonar/radarr to cancel the download?

**Comment by kstanleyadams** [comment]
I tested it and it seems to be working fine. Thank you! Is there any functionality lost except the tag protection?

**Comment by ManiMatter** [comment]
> If I don’t specify the url, then your tool will not be able to remove the failed downloads from rdt if I understand correctly. Or are you using sonar/radarr to cancel the download?

Strictly speaking, decluttarr does not remove torrents. It tells sonarr to remove them, thats why decluttarr doesnt need the url for removal



> I tested it and it seems to be working fine. Thank you! Is there any functionality lost except the tag protection?

Yes, protection for private trackers; and better reliability for speed/status detection, but not critical.
