### ISSUE TITLE
[Bug] Qbit cookie needs refresh

### ISSUE THREAD

**Issue by OmarAlKhamis** [ManiMatter/decluttarr#197]
Hello,
i have installed decluttarr and i'm loving it so far, it seems to work for me with radarr and sonarr except for one thing
i don't think that it is actually counting to 3 to add the torrent to the blacklist.

below is my config and a picture showing the log filtered by the release name, showing it removing 1 torrent again and again without increasing the count from 1, and not adding it to the black list. can you help me please.

notable mention is i increased the default 10 minutes loop to 360 minutes ( 6 hours ) i don't htink i need to check more than 4 times a day.

my YAML config :

        version: "3.3"
        services:
          decluttarr:
            image: ghcr.io/manimatter/decluttarr:latest
            container_name: decluttarr
            restart: always
            environment:
              TZ: Asia/Riyadh
              PUID: 1000
              PGID: 1000
        
              ## General
              # TEST_RUN: True
              # SSL_VERIFICATION: False
              LOG_LEVEL: VERBOSE
        
              ## Features 
              REMOVE_TIMER: 360
              REMOVE_FAILED: True
              REMOVE_FAILED_IMPORTS: True
              REMOVE_METADATA_MISSING: True
              REMOVE_MISSING_FILES: True
              REMOVE_ORPHANS: True
              REMOVE_SLOW: True
              REMOVE_STALLED: True
              REMOVE_UNMONITORED: True
              RUN_PERIODIC_RESCANS: |
                {
                  "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
                  "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
                }
        
              # Feature Settings
              PERMITTED_ATTEMPTS: 3
              NO_STALLED_REMOVAL_QBIT_TAG: "Don't Kill"
              MIN_DOWNLOAD_SPEED: 100
              FAILED_IMPORT_MESSAGE_PATTERNS: |
                [
                  "Not a Custom Format upgrade for existing",
                  "Not an upgrade for existing"
                ]
        
              ## Radarr
              RADARR_URL: LINK
              RADARR_KEY: LINK
        
              ## Sonarr
              SONARR_URL: LINK
              SONARR_KEY: LINK
        
              ## Lidarr (commented out)
              # LIDARR_URL: http://lidarr:8686
              # LIDARR_KEY: $LIDARR_API_KEY
        
              ## Readarr (commented out)
              # READARR_URL: http://readarr:8787
              # READARR_KEY: $READARR_API_KEY
        
              ## Whisparr (commented out)
              # WHISPARR_URL: http://whisparr:6969
              # WHISPARR_KEY: $WHISPARR_API_KEY
        
              ## qBittorrent
              QBITTORRENT_URL: LINK
              QBITTORRENT_USERNAME: LINK
              QBITTORRENT_PASSWORD: LINK

Filtered Log by the release in question, i have many other releases with same issue but this is an example
![image](https://github.com/user-attachments/assets/bcd9d489-f088-4c5f-939a-3d1552e157bb)

**Comment by ManiMatter** [comment]
Can you pls provide logs on VERBOSE level

**Comment by OmarAlKhamis** [comment]
> Can you pls provide logs on VERBOSE level

I’m Sorry I’m not too technical could ypu explain hown i can do that ?

the screen shot i shared is from dozzler 

—- edit
I think i understand you know i will get logs shortly

**Comment by OmarAlKhamis** [comment]
> Can you pls provide logs on VERBOSE level

i think this is the complete log with `info nad VERBOSE
[decluttarr-2024-11-30T23-02-09.log](https://github.com/user-attachments/files/17967264/decluttarr-2024-11-30T23-02-09.log)

**Comment by ManiMatter** [comment]
Thank you
```
2024-11-19T16:49:37.107187706Z HTTP Error: 403 Client Error: Forbidden for url: http://192.168.1.150:8081/api/v2/torrents/info
2024-11-19T16:49:37.135024551Z TypeError: 'NoneType' object is not iterable
```

smells like a bug to me.
Could you pls also share debug-level logs?

could you also share a screenshot of your qbittorrent & your *arr-queue

**Comment by OmarAlKhamis** [comment]
> Thank you
> 
> ```
> 2024-11-19T16:49:37.107187706Z HTTP Error: 403 Client Error: Forbidden for url: http://192.168.1.150:8081/api/v2/torrents/info
> 2024-11-19T16:49:37.135024551Z TypeError: 'NoneType' object is not iterable
> ```
> 
> smells like a bug to me. Could you pls also share debug-level logs?
> 
> could you also share a screenshot of your qbittorrent & your *arr-queue


do i need to redeploy the container with the option DEBUG ? Or is there another way to get it ?

**Comment by ManiMatter** [comment]
Just stop the container, change the log level of it to debug and up it again.

**Comment by OmarAlKhamis** [comment]
> Just stop the container, change the log level of it to debug and up it again.

thanks for clarifying
i did that and i also reduced the cycle time to 2 minutes to get more cycles in the log
please find attached, thanks for the help

[decluttarr-2024-12-02T06-42-07.log](https://github.com/user-attachments/files/17973640/decluttarr-2024-12-02T06-42-07.log)

**Comment by OmarAlKhamis** [comment]
Hmmm, i'm not really expert on this but it seems to me that reducing the time to 2 minutes is working and attempts are counting
could it be because i had 6 hours ? is there a workaround ? is there any specific max timer that i should observe ?

the reason i wanted 6 hours is because sometimes seeding time on some items is not consistent 24 hrs, sometimes it is dependant on when people turn on their devices which is a 24-hour range of possiblity, that's why i put 6 hours to cover at least 3/4 of the whole day with waiting... .hmmm


`
      2024-12-02T06:36:29.411087511Z [INFO]: >>> Detected stalled download (3 out of 3 permitted times): Detective Conan Zero the Enforcer 2018 JAPANESE PROPER 1080p BluRay H264 AAC VXT ORARBG
      2024-12-02T06:39:05.293318861Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): My 600-Lb Life Where Are They Now S04E10 Nicole and Ashley D 480p x264-mSD [eztv]
      2024-12-02T06:39:05.293359445Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): The Walking Dead S01 1080p AMZN WEBRip DDP2 0 x265 SiGMA rartv ORARBG
      2024-12-02T06:39:05.293407695Z [INFO]: >>> Detected stalled download (2 out of 3 permitted times): My 600-Lb Life Where Are They Now S04E12 Sean and Dottie WEB x264-APRiCiTY [eztv]
      2024-12-02T06:39:05.293444212Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): My 600 lb Life Where Are They Now S05E01 720p WEB x264-57CHAN [eztv]
      2024-12-02T06:39:05.293477792Z [INFO]: >>> Detected stalled download (2 out of 3 permitted times): my.600-lb.life.where.are.they.now.s04e11.lupe.and.brittani.720p.web.x264-apricity[eztv].mkv[eztvx.to]
`

**Comment by Jorman** [comment]
Hi, sorry to intrude, I have a couple of questions that may relate back to this topic, if I may, I take the opportunity to ask for an explanation so that I can better understand how to set up the program.

For `SLOW` downloads I read that `If the increase in the downloaded file size of a download is less than this value between two consecutive checks, the download is considered slow and is removed if happening more ofthen than the permitted attempts`, so for example if the time between one check and the next 6 hours pass and the limit of 100 KBytes/s, the download will be reported as `SLOW` if:
```
Download speed = 100 KBytes per second
Time = 6 hours
----------------
6 hours = 6 × 60 × 60 = 21,600 seconds
Now let's calculate total bytes downloaded:

Total bytes = 100 KB/s × 21,600 s = 2,160,000 KB
So after 6 hours you should have downloaded about 2,109.375 MB (or about 2.11 GB).
```
And on the second check what happens, +2.11Gb from the last check or from the initial one?

Second question but on `STALLED` downloads.
I understand that the download is considered STALLED only if our *Arr reports it as stalled, correct?

This means that if at the time of checking *Arr reports the download as `STALLED`, then the program will note it, otherwise the counter will be reset. So this, with very large files maybe with few sources and sometimes slow, could be a problem right?

Especially if the check is done once every 6 hours instead of once every 10 minutes, the more diluted the checks are over time, the more likely it is that the download is temporarily stopped

What do you think @ManiMatter about an additional check for file size with also a dedicated counter? For example, if between one check and the next the file size has not changed, then the counter is increased and after X attempts the download is reported as stopped, unsourced and removable.

In my experience, so just from what I have noticed with some of my downloads, I have noticed that some of these situations do happen, maybe not always, but they do happen.

Sorry for the intrusion, but it seemed to be consistent with what was discussed

**Comment by ManiMatter** [comment]
> And on the second check what happens, +2.11Gb from the last check or from the initial one?

Not sure if that's a leading question - as the documentation says: between two consecutive checks. Thus from the last check, not from the initial one.


> Second question but on `STALLED` downloads. I understand that the download is considered STALLED only if our *Arr reports it as stalled, correct?

Correct.

> This means that if at the time of checking *Arr reports the download as `STALLED`, then the program will note it, otherwise the counter will be reset. So this, with very large files maybe with few sources and sometimes slow, could be a problem right?

No, not a problem. If sometimes it's stalled, but it recuperates in between, then it's correctly "healed". Only if it violates the consecutive checks too many times its removed.


> What do you think @ManiMatter about an additional check for file size with also a dedicated counter? For example, if between one check and the next the file size has not changed, then the counter is increased and after X attempts the download is reported as stopped, unsourced and removable.

Isn't that exactly what the slow download check does? Regarless of the download's state, if it's too slow, it's getting killed if found to be slow too many times.

**Comment by ManiMatter** [comment]
> Hmmm, i'm not really expert on this but it seems to me that reducing the time to 2 minutes is working and attempts are counting could it be because i had 6 hours ? is there a workaround ? is there any specific max timer that i should observe ?
> 
> the reason i wanted 6 hours is because sometimes seeding time on some items is not consistent 24 hrs, sometimes it is dependant on when people turn on their devices which is a 24-hour range of possiblity, that's why i put 6 hours to cover at least 3/4 of the whole day with waiting... .hmmm
> 
> `2024-12-02T06:36:29.411087511Z [INFO]: >>> Detected stalled download (3 out of 3 permitted times): Detective Conan Zero the Enforcer 2018 JAPANESE PROPER 1080p BluRay H264 AAC VXT ORARBG 2024-12-02T06:39:05.293318861Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): My 600-Lb Life Where Are They Now S04E10 Nicole and Ashley D 480p x264-mSD [eztv] 2024-12-02T06:39:05.293359445Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): The Walking Dead S01 1080p AMZN WEBRip DDP2 0 x265 SiGMA rartv ORARBG 2024-12-02T06:39:05.293407695Z [INFO]: >>> Detected stalled download (2 out of 3 permitted times): My 600-Lb Life Where Are They Now S04E12 Sean and Dottie WEB x264-APRiCiTY [eztv] 2024-12-02T06:39:05.293444212Z [INFO]: >>> Detected stalled download (1 out of 3 permitted times): My 600 lb Life Where Are They Now S05E01 720p WEB x264-57CHAN [eztv] 2024-12-02T06:39:05.293477792Z [INFO]: >>> Detected stalled download (2 out of 3 permitted times): my.600-lb.life.where.are.they.now.s04e11.lupe.and.brittani.720p.web.x264-apricity[eztv].mkv[eztvx.to]`

It's hard to tell why the 6h gave an error but the 2min one works without having debug logs for the 6h one.
I understand why you want to keep the 6h frequency, which in theory should work. 

Please switch back to the 6h interval, and once you have 1-2 iterations done (that don't work) please share the debug logs.
I will look at it and hopefully find why we get the problem and try to fix it.

**Comment by OmarAlKhamis** [comment]
> Please switch back to the 6h interval, and once you have 1-2 iterations done (that don't work) please share the debug logs. I will look at it and hopefully find why we get the problem and try to fix it.

thanks for keeping on top of this
i ran it for sometimes but with a frequency of 1 hour instead of 6, and i think it is failing, i'm seeing 36 matches of 1 specific download that is always on attempt 1 - i'm doing this using ctrl+F in the logs. i think this is running for +36 iterations now

kindly see the file below

[decluttarr-2024-12-03T18-52-29.log](https://github.com/user-attachments/files/17997642/decluttarr-2024-12-03T18-52-29.log)


as another example you can observe this line is repeated 33 times:
`[INFO]: >>> Detected missing metadata download (1 out of 3 permitted times): Undercover Billionaire S02E09 Dumpster Fire 720p WEB h264 B2B rartv ORARBG
`

**Comment by ManiMatter** [comment]
> 2024-12-02T21:53:49.901666934Z [VERBOSE]: --------------------------------------------------
> 2024-12-02T21:53:49.907104918Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:8081
> 2024-12-02T21:53:49.948021804Z [DEBUG]: http://192.168.1.150:8081 "GET /api/v2/torrents/info HTTP/11" 403 9
> 2024-12-02T21:53:50.014990217Z **HTTP Error: 403 Client Error: Forbidden for url: http://192.168.1.150:8081/api/v2/torrents/info**
> 2024-12-02T21:53:50.023021056Z TypeError: 'NoneType' object is not iterable
> 2024-12-02T21:54:03.960727761Z [DEBUG]: Using selector: EpollSelector
> 2024-12-02T21:54:04.020051199Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:7878
> 2024-12-02T21:54:04.023114531Z [DEBUG]: http://192.168.1.150:7878 "GET /api/v3/system/status HTTP/11" 200 None
> 2024-12-02T21:54:04.025286519Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:8989
> 2024-12-02T21:54:04.028028918Z [DEBUG]: http://192.168.1.150:8989 "GET /api/v3/system/status HTTP/11" 200 None
> 2024-12-02T21:54:04.029098028Z [INFO]: ##################################################
> 2024-12-02T21:54:04.029173525Z [INFO]: **Decluttarr - Application Started!**


What you see in these logs is the following:
- for some reason the call to the `/api/v2/torrents/info` fails, which causes decluttarr to restart
- since it's restarting, the count restarts at 1

so it's not about the counting, but we need to figure out why your call to qbit fails.

What can you tell me about your qbit? Version and docker image you are using?
Can you also share a screenshot pls

**Comment by ManiMatter** [comment]
> 2024-12-02T21:53:49.901666934Z [VERBOSE]: --------------------------------------------------
> 2024-12-02T21:53:49.907104918Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:8081
> 2024-12-02T21:53:49.948021804Z [DEBUG]: http://192.168.1.150:8081 "GET /api/v2/torrents/info HTTP/11" 403 9
> 2024-12-02T21:53:50.014990217Z **HTTP Error: 403 Client Error: Forbidden for url: http://192.168.1.150:8081/api/v2/torrents/info**
> 2024-12-02T21:53:50.023021056Z TypeError: 'NoneType' object is not iterable
> 2024-12-02T21:54:03.960727761Z [DEBUG]: Using selector: EpollSelector
> 2024-12-02T21:54:04.020051199Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:7878
> 2024-12-02T21:54:04.023114531Z [DEBUG]: http://192.168.1.150:7878 "GET /api/v3/system/status HTTP/11" 200 None
> 2024-12-02T21:54:04.025286519Z [DEBUG]: Starting new HTTP connection (1): 192.168.1.150:8989
> 2024-12-02T21:54:04.028028918Z [DEBUG]: http://192.168.1.150:8989 "GET /api/v3/system/status HTTP/11" 200 None
> 2024-12-02T21:54:04.029098028Z [INFO]: ##################################################
> 2024-12-02T21:54:04.029173525Z [INFO]: **Decluttarr - Application Started!**


What you see in these logs is the following:
- for some reason the call to the `/api/v2/torrents/info` fails, which causes decluttarr to restart
- since it's restarting, the count restarts at 1

so it's not about the counting, but we need to figure out why your call to qbit fails.

UPDATE: 
I think I know why. when decluttar starts, it grabs a cookie to authenticate with qbit. 
Probably the cookie expires and therefore qbit rejects the authentication. 

I need to think how to solve that.

**Comment by OmarAlKhamis** [comment]
> UPDATE: I think I know why. when decluttar starts, it grabs a cookie to authenticate with qbit. Probably the cookie expires and therefore qbit rejects the authentication.
> 
> I need to think how to solve that.

it's interesting
i'm not really sure
i have watchtower installed so all of my docker containers including qbittorrents are updated to latest

i installed my qbittorrent using this guide i'm sure https://mariushosting.com/how-to-install-qbittorrent-on-your-synology-nas/
i'm using a synology NAS and i do follow mariushosting guides generally.


i have attached pictures below that may be of help ?

![Screenshot 2024-12-03 231710](https://github.com/user-attachments/assets/cf161db8-c2ac-47ce-8527-1d4976daa9e0)
![Screenshot 2024-12-03 231503](https://github.com/user-attachments/assets/0c1b2a20-a410-4b96-9ce8-e65927eb31c8)
![Screenshot 2024-12-03 231516](https://github.com/user-attachments/assets/be81e318-c7d2-437b-8bce-af0a56619e2f)
![Screenshot 2024-12-03 231519](https://github.com/user-attachments/assets/e4d9b0b0-2ff2-4b9a-bb17-e10a93b9402d)
![Screenshot 2024-12-03 231526](https://github.com/user-attachments/assets/bf1b3dc7-5d63-4c34-8fac-f873e61f042e)
![Screenshot 2024-12-03 231532](https://github.com/user-attachments/assets/c9c7fdae-99fd-4a81-b27c-4792ea22727a)
![Screenshot 2024-12-03 231535](https://github.com/user-attachments/assets/13e727e5-8014-40ec-965a-c3348690423c)
![Screenshot 2024-12-03 231539](https://github.com/user-attachments/assets/0092e334-7b23-43dc-a0b0-bd3635a9be0d)
![Screenshot 2024-12-03 231543](https://github.com/user-attachments/assets/455cb221-c737-44f6-ac09-63d024b419b7)
![Screenshot 2024-12-03 231548](https://github.com/user-attachments/assets/d0698316-7f24-46d4-a667-b9ca0bea5d16)

**Comment by OmarAlKhamis** [comment]
it will be interesting to know if this problem is happening to me only (declutarr restarting cuz of qbittorrents when increasing the time interval) or it's only my install environment that is creating this problem,

**Comment by ManiMatter** [comment]
I've added a fix. Could you please pull the docker container version "refresh-qbit-cookie" (instead of "latest") and test it again and provide the debug logs? 

This version refreshes the cookie on every run. If successful, I will then merge this fix to latest

**Comment by Jorman** [comment]
> > And on the second check what happens, +2.11Gb from the last check or from the initial one?
> 
> Not sure if that's a leading question - as the documentation says: between two consecutive checks. Thus from the last check, not from the initial one.

Right actually says between two checks, so always between the first and second!
 
> > Second question but on `STALLED` downloads. I understand that the download is considered STALLED only if our *Arr reports it as stalled, correct?
> 
> Correct.
> 
> > This means that if at the time of checking *Arr reports the download as `STALLED`, then the program will note it, otherwise the counter will be reset. So this, with very large files maybe with few sources and sometimes slow, could be a problem right?
> 
> No, not a problem. If sometimes it's stalled, but it recuperates in between, then it's correctly "healed". Only if it violates the consecutive checks too many times its removed.

It has happened to me more than once that a `STALLED` download, after a few days was completed, so it means that in the meantime the sources for completion have returned. Maybe I just "fear" the fact that if at the time of checking `decluttarr` for `*Arr` the torrent is `STALLED`, a potential `good` download is discarded.
Maybe I have not yet understood and decided well how to set `decluttarr` according to my personal needs, I am afraid to set too "rigid" a configuration and to penalize any "slow" downloads (searching for old things can happen) but still complete
That's why I asked you what you think about the option related to increasing size but unrelated to time, because `*Arr` often confuse slow torrents as `STALLED` torrents, while a stopped download never changes in size.

> 
> > What do you think @ManiMatter about an additional check for file size with also a dedicated counter? For example, if between one check and the next the file size has not changed, then the counter is increased and after X attempts the download is reported as stopped, unsourced and removable.
> 
> Isn't that exactly what the slow download check does? Regarless of the download's state, if it's too slow, it's getting killed if found to be slow too many times.

Not exactly the same, definitely very similar, maybe I can set 1 KBytes/s and so in 10 minutes it's about 0.6Mb, then I increase the `PERMITTED_ATTEMPTS` maybe to a high value like 288, so I have two days of controls and if the trigger goes off it means the download is stopped, however the `PERMITTED_ATTEMPTS` don't only refer to slow torrents.
What do you say can this work or do you recommend doing it differently?

**Comment by ManiMatter** [comment]
@Jorman  - do you mind creating a separate issue for these questions please?

**Comment by OmarAlKhamis** [comment]
> I've added a fix. Could you please pull the docker container version "refresh-qbit-cookie" (instead of "latest") and test it again and provide the debug logs?
> 
> This version refreshes the cookie on every run. If successful, I will then merge this fix to latest

Thanks
I will do it once i go back home and provide the logs tomorrow after some cycles 

Update, i just pulled the new instance and run it with time frequency of 6 hours, i can see the log and that i already have some stalled and some missing meta data which will be good to track over the next 24 hours and see the attempt count and the behaviur, please see picture below

i will wait at least 2 cycles completed then upload the logs


![image](https://github.com/user-attachments/assets/47baac91-0eff-430c-9b81-50e8151f083f)

**Comment by OmarAlKhamis** [comment]
[decluttarr-2024-12-04T22-24-36.log](https://github.com/user-attachments/files/18014808/decluttarr-2024-12-04T22-24-36.log)

**Comment by ManiMatter** [comment]
Good news - in your latest logs, I don't see this error anymore:
> > 2024-12-02T21:53:49.948021804Z [DEBUG]: http://192.168.1.150:8081 "GET /api/v2/torrents/info HTTP/11" 403 9
> > 2024-12-02T21:53:50.014990217Z **HTTP Error: 403 Client Error: Forbidden for url: http://192.168.1.150:8081/api/v2/torrents/info**

Instead, I see the following, which is correct
`2024-12-04T07:36:36.241959065Z [DEBUG]: qBit cookie refreshed!`


Overall, seems solved. However, I have not seen any removals (I see 3/3 but not 4/3), that's probably because you have only run 3 cycles so far, and in 6h you will see the removals.

Can you please confirm back that the removals take place? then we know the bug is fixed for sure.

**Comment by ManiMatter** [comment]
any verdict?

**Comment by OmarAlKhamis** [comment]
> any verdict?

Heey
thanks for keeping on top of this

i think it's working ?
i'm not sure because my qbit queue is still long, but that maybe becauase the serise i'm following are not seeded well and sonarr is trying over couple of days to grap a good one ( cuz my frequency is 6 hrs )

anyway, i noticed the following:
1. sonarr blacklist is being populated
2. things are reaching 3 out of 3 and 4 out of 3

i have one question
what does this tag mean ??

`[INFO]: >>> Download no longer marked as stalled: My 600 Lb Life S09E10 Shannons Journey 1080p WEB h264 B2B rartv ORARBG
`

please find the log here :

[decluttarr-2024-12-06T08-40-33.log](https://github.com/user-attachments/files/18035180/decluttarr-2024-12-06T08-40-33.log)

here are screenshots of qbit and sonarr blacklist:

i can see from the qbit screen that "date added" indicates all of those are fresh torrents added recently ( within 3x cycles of 6 hours )
what do you think ? is it resolved ?

![Screenshot 2024-12-06 114503](https://github.com/user-attachments/assets/c816ca76-6112-40b5-9b8c-a7722ff2abbc)
![Screenshot 2024-12-06 114633](https://github.com/user-attachments/assets/8c24b70e-d43c-4890-a60a-590b35e702eb)


radarr blacklist too btw

![image](https://github.com/user-attachments/assets/96918492-9ca8-4bab-8b3d-ceabed72814e)

**Comment by ManiMatter** [comment]
Yes looks good.
4/3 means that it was found stalled too many times. Thats when its removed

Not stalled anymore means that it recovered in between.
