### ISSUE TITLE
[Feature request] add option to manage stalled download, without consider *Arr status

### ISSUE THREAD

**Issue by Jorman** [ManiMatter/decluttarr#201]
Hi, I finally took the time to create the new topic, sorry I wrote in the other one.

If you think it makes sense, I would like you to consider including a check to determine if a download is really stopped
I know that both checks exist for both `SLOW` and `STALLED` downloads and both rely on PERMITTED_ATTEMPTS to determine the maximum tolerated number of attempts before taking action.

I know it may sound redundant but I think it may have its own motivation, surely they are the minority, but `rare` downloads happen with few sources because they are very old or little known/shared and often it is just them, there is not much alternative.
I'm still testing and trying to set up the program in the best possible way that fits my case, but if I set `decluttarr` to do very close checks, I have to increase the number of `PERMITTED_ATTEMPTS` and vice versa, this allows me not to trigger `STALLED` and/or `SLOW` downloads and then I also have to put a low limit for the speed if the checks are very far apart.
All of this then comes at the expense of those `standard` downloads, which instead `decluttarr` helps to handle perfectly and in case of problems manages to provide valuable automaticity.

So I wonder if and what about including a check on file size only, with corresponding counter, if then the file remains the same size `X` times then it is set as to be removed and follows all the normal logic of `decluttarr`, blacklist, trigger for new search etc.
Surely such a file would be flagged as `STALLED` even by our `*Arr`, but without the option there is a risk that a slow file with few sources would never be downloaded because the checks would remove it first.

The only real flaw in all this reasoning lies in the fact that if the control is implemented, people to use it will have to make choices during the configuration phase, but this will then depend on what and how they use the various `*Arr` and configure `decluttarr` accordingly.

Considerations in this regard?
Does it seem so unnecessary as a possible additional option?

J

**Comment by ManiMatter** [comment]
When you have a rare download  you can protect it with the "Don't Kill" tag - problem solved. No?

**Comment by Jorman** [comment]
Hi,
I have never used this feature, I have to set the TAG by hand on the selected torrents in qBittorrent, right?
I guess it works, it's a different alternative but it protects the torrent 100%, with no possibility of automatic removal, unlike an eventual implementation of the new feature
I will try it on the next particular torrent!

**Comment by ManiMatter** [comment]
Yes you set the tag within qbit

I‘ll close this as I dont see a gap
- for rare downloads, users may want to accept long periods of stallness and can protect against removal usibg tag
- For all other downloads, the consecutive misses counter the problem of downloads being removed too quickly
-

**Comment by Jorman** [comment]
Hi,
I ask you, if you want, to keep this Feature request open, even in low priority, I can try to see if I can implement it, I don`t guarantee, maybe I need some advice, it was bash ok, but Python I am not expert, I am converting some of my scripts but it`s another matter.
As you also say in the home, `qBittorrent is recommended but not required`, there are some limitations and this Feature would help for those clients that are not `qBittorrent`, where so you can't use the tags or the various limitations given just by the fact that you don't use the `qBittorrent` client, by doing that you can also avoid using the `STALLED` feature of `*Arr` which is less accurate
It becomes interested because you can run multiple instances, each configured differently, excluding the various download clients one at a time, obviously enabling/disabling the various features.
