### ISSUE TITLE
Queue cleanup not clearing "Waiting to import"

### ISSUE THREAD

**Issue by kstanleyadams** [ManiMatter/decluttarr#205]
> [INFO   ]: ##################################################
> [INFO   ]: Decluttarr - Application Started!
> [INFO   ]: 
> [INFO   ]: Like this app? Thanks for giving it a ⭐️ on GitHub!
> [INFO   ]: https://github.com/ManiMatter/decluttarr/
> [INFO   ]: 
> [INFO   ]: *** Current Settings ***
> [INFO   ]: Version: v1.50.1
> [INFO   ]: Commit: 295275d
> [INFO   ]: 
> [INFO   ]: True | Removing failed downloads (REMOVE_FAILED)
> [INFO   ]: True | Removing failed imports (REMOVE_FAILED_IMPORTS)
> [VERBOSE]: > Imports with a warning flag are considered failed if the status message contains any of the following patterns:
> [VERBOSE]:   - "Not a Custom Format upgrade for existing"
> [VERBOSE]:   - "Not an upgrade for existing"
> [VERBOSE]:   - "Invalid video file"
> [VERBOSE]:   - "No files found are eligible for import"
> [VERBOSE]:   - "Found archive file"
> [VERBOSE]:   - "File is suspected multi-part file"
> [VERBOSE]:   - "Found matching movie via grab history"
> [VERBOSE]:   - "Invalid Magnet"
> [INFO   ]: True | Removing downloads missing metadata (REMOVE_METADATA_MISSING)
> [INFO   ]: True | Removing downloads missing files (REMOVE_MISSING_FILES)
> [INFO   ]: True | Removing orphan downloads (REMOVE_ORPHANS)
> [INFO   ]: False | Removing slow downloads (REMOVE_SLOW)
> [INFO   ]: True | Removing stalled downloads (REMOVE_STALLED)
> [INFO   ]: False | Removing downloads belonging to unmonitored items (REMOVE_UNMONITORED)
> [INFO   ]: True/True (SONARR) | Search missing/cutoff-unmet items. Max queries/list: 3. Min. days to re-search: 7 (RUN_PERIODIC_RESCANS)
> [INFO   ]: True/True (RADARR) | Search missing/cutoff-unmet items. Max queries/list: 3. Min. days to re-search: 7 (RUN_PERIODIC_RESCANS)
> [INFO   ]: 
> [INFO   ]: Running every: 0 days 0 hours 10.0 minutes
> [INFO   ]: Permitted number of times before stalled/missing metadata/slow downloads are removed: 6
> [INFO   ]: 
> [INFO   ]: *** Configured Instances ***
> [INFO   ]: Radarr: http://192.168.0.23:7878
> [INFO   ]: Sonarr: http://192.168.0.23:8989
> [INFO   ]: 
> [INFO   ]: *** Check Instances ***
> [INFO   ]: OK | Radarr
> [INFO   ]: OK | Sonarr
> [INFO   ]: 
> [INFO   ]: ##################################################
> [INFO   ]: 
> [VERBOSE]: --------------------------------------------------
> [VERBOSE]: Cleaning queue on Radarr:
> [VERBOSE]: >>> Queue is clean.
> [VERBOSE]: >>> Rescan: All missing items have recently been scanned for, thus nothing to rescan.
> [VERBOSE]: >>> Rescan: All cutoff items have recently been scanned for, thus nothing to rescan.
> [VERBOSE]: Cleaning queue on Sonarr:
> [VERBOSE]: >>> Queue is clean.
> [VERBOSE]: >>> Rescan: All missing items have recently been scanned for, thus nothing to rescan.
> [VERBOSE]: >>> Rescan: All cutoff items have recently been scanned for, thus nothing to rescan.
> [VERBOSE]: 
> [VERBOSE]: Queue clean-up complete!

I have various items in Radarr with status "Downloaded - Waiting to Import". The reason given is "Found archive file, might need to be extracted"

These are not being detected and removed by decluttarr for some reason. Do you see an obvious config issue?

**Comment by ManiMatter** [comment]
The pattern not listed?

[VERBOSE]: > Imports with a warning flag are considered failed if the status message contains any of the following patterns:
[VERBOSE]: - "Not a Custom Format upgrade for existing"
[VERBOSE]: - "Not an upgrade for existing"
[VERBOSE]: - "Invalid video file"
[VERBOSE]: - "No files found are eligible for import"
[VERBOSE]: - "Found archive file"
[VERBOSE]: - "File is suspected multi-part file"
[VERBOSE]: - "Found matching movie via grab history"
[VERBOSE]: - "Invalid Magnet"

**Comment by kstanleyadams** [comment]
I have "Found archive file" as a pattern. My understanding that this should match "Found archive file, might need to be extracted"

**Comment by ManiMatter** [comment]
Could you post the /queue response from your *arr pls? Ie from your browser network tab

**Comment by ManiMatter** [comment]
ping?

**Comment by kstanleyadams** [comment]
Hi sorry. I had cleared my queue already and have been unable to reproduce the issue, even by downloading the same torrents again. Please close the ticket and I will come back if I see it again.
