### ISSUE TITLE
Multiple Sonarr/Radarr Support Needed

### ISSUE THREAD

**Issue by egadgetboy** [ManiMatter/decluttarr#207]
Like others, I have seperate Sonarr/Radarr instances for 4K

Please adjust to allow for multiple instances.

Example:

      ## Sonarr4K
      SONARR4K_URL: http://192.168.1.220:8990
      SONARR4K_KEY: blah

**Comment by ManiMatter** [comment]
Duplicate

**Comment by egadgetboy** [comment]
I don’t see a duplicate issue open for this

**Comment by ManiMatter** [comment]
Check the closed issues.

**Comment by egadgetboy** [comment]
Ah I see now, thanks. Hopefully you will consider putting that on the roadmap. I know quite a few who run multiple instances. It keeps the queues much cleaner.On Dec 10, 2024, at 10:20 AM, ManiMatter ***@***.***> wrote:﻿
Check the closed issues.
