### ISSUE TITLE
[Feature request] - Save attempts iterations to a persistent file, if docker method is used

### ISSUE THREAD

**Issue by Jorman** [ManiMatter/decluttarr#208]
Hi,

correct me if I'm wrong but I just realized that if the docker restarts you lose the results of the various attempts made.
Could a file be created to save the information about the various iterations? So that you don't have to restart from 0 in case of a docker restart,

**Comment by ManiMatter** [comment]
not planned; that would require a entire re-design of the app, inc. some writing to disk or DB. 
keep your docker running, and all is golden ;)

**Comment by Jorman** [comment]
Well, for disk writes it is as it would happen for https://github.com/ManiMatter/decluttarr/issues/200 just on a dedicated file, to be read at startup and to be written at every check
Certainly the more docker is running the better, it happens though that either the machine or docker or decluttarr itself has to restart, upgrade or otherwise, the write to file would be useful for those who use decluttarr with long times before the program intervenes.

What are your thoughts on this?

**Comment by ManiMatter** [comment]
Not planning to add it. If somebody wants to code it, I‘m ok with it…
