### ISSUE TITLE
[Feature request] Readarr support

### ISSUE THREAD

**Issue by waredrive** [ManiMatter/decluttarr#21]
Hi,
Would it be possible to make decluttarr work with readarr as well?

**Comment by ManiMatter** [comment]
I have added it to the :dev version. I don't have readarr myself, so developped it "blindly". 
Could you kindly test and revert it it works for you?

**Comment by ManiMatter** [comment]
Hi @waredrive 
Just checking if you were able to test the feature (already in ‚latest’) and whether this ticket can be closed?

**Comment by ManiMatter** [comment]
Closing since no feedback; assuming working fine.
