### ISSUE TITLE
[Bug] IGNORED_DOWNLOAD_CLIENTS type lint is wrong

### ISSUE THREAD

**Issue by TheFabbiusCorp** [ManiMatter/decluttarr#213]
In DSM, after pasting the docker-compose.yml file in to create a new containers, the linter goes mad on the IGNORED_DOWNLOAD_CLIENTS line because it expects a string or else, but not a list. The changes cannot be saves if the linter "warning" is not fixed. Once done changing the list into a string and running the built the container, the logs show the following error: `[ ERROR ]: The value retrieved for [feature_settings]: IGNORED_DOWNLOAD_CLIENTS is emulerr and cannot be converted to data type <class 'list'>`.

Only practical way to overcome this is to change the IGNORED_DOWNLOAD_CLIENTS parameter back to a list before running the container.

Two solutions come up to my mind:
1. Fix the type definition so the linter doesn't bother.
2. Make the variable optional so the container runs fine (as of now it shuts down if that variable is not present).

**Comment by ManiMatter** [comment]
Hi
not sure I understand. What is DSM please?

What do you mean by 

> it expects a string or else, but not a list

decluttarr needs a list, as per Readme, and if not provided defaults to empty list:

> IGNORED_DOWNLOAD_CLIENTS
> …
> Type: List
> Is Mandatory: No (Defaults to [], which means no download clients are skipped


Thus not sure I follow what the bug is you describe. Can you please elaborate

**Comment by TheFabbiusCorp** [comment]
Hey @ManiMatter, DSM is the OS for Synology NAS. It can run Docker, so I can use Docker Compose. In the UI to add the yml file suggested in the Readme, I get a warning on the IGNORED_DOWNLOAD_CLIENTS variable because for some reason it expects a string or a number, not a list. I know it is strange, because I can see [here](https://github.com/ManiMatter/decluttarr/blob/dev/config/definitions.py#L30) that the type for that variable is a list, but I still get the error. So I was wondering if there is some other place where this variable is used as a string... maybe [here](https://github.com/ManiMatter/decluttarr/blob/dev/src/utils/shared.py#L74) or [here](https://github.com/ManiMatter/decluttarr/blob/dev/src/utils/loadScripts.py#L106)? 🤔

**Comment by ManiMatter** [comment]
i struggle to understand if its a matter of the code inside the app, or a matter of the yml format

when you get the linter issues, is that on execution or even before when you paste the yml into synology?

can you pls paste here the yml you are using?

**Comment by ManiMatter** [comment]
ping?

**Comment by TheFabbiusCorp** [comment]
> i struggle to understand if its a matter of the code inside the app, or a matter of the yml format
> 
> 
> 
> when you get the linter issues, is that on execution or even before when you paste the yml into synology?
> 
> 
> 
> can you pls paste here the yml you are using?

It happens when I paste the yaml into synology. I will send a picture later.

**Comment by TheFabbiusCorp** [comment]
Here are the two cases @ManiMatter 

Not working
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/2410bd44-0c3f-4644-a996-30c7de6e7a7d" />

Working
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/cd49e37f-9333-404e-a750-fc8a2385959e" />

**Comment by ManiMatter** [comment]
> Not working <img alt="image" width="1245" src="https://private-user-images.githubusercontent.com/8267992/396825518-2410bd44-0c3f-4644-a996-30c7de6e7a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MTg1ODgsIm5iZiI6MTczNDUxODI4OCwicGF0aCI6Ii84MjY3OTkyLzM5NjgyNTUxOC0yNDEwYmQ0NC0wYzNmLTQ2NDQtYTk5Ni0zMGM3ZGU2ZTdhN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMTAzODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTc0OTQxZjc3NTRlNTU4ZThkYmEyYWM0MzdkZjNmMTNiZDY0M2FkMDU2M2YxYzA1NjVjNWM0YWUwNTBlMWZkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.l_mk_NU_mQ5Wm_xBNqceMtPTLsx5sHil_bv2IHanMFE">
> 


Are you not just missing the quotes?
`      IGNORED_DOWNLOAD_CLIENTS: ["emulerr"]`

**Comment by TheFabbiusCorp** [comment]
Same same:
<img width="459" alt="image" src="https://github.com/user-attachments/assets/c64a51a6-1c4a-43d3-888a-461c8db9d600" />

**Comment by ManiMatter** [comment]
Im tapping in the dark.

are you even using emulerr/want to exclude sny agents?

if not, can you not simply remove that entire key from your compose?

**Comment by TheFabbiusCorp** [comment]
I don't need emulerr and I tried to remove the whole key, but when I do and save, once I start the container I get more errors and it stops.

Anyway, if you cannot reproduce it and since I have found a workaround (changing the value in the generated container yaml file), you can stop looking into it and close the issue if you prefer.

**Comment by Sc0ttmeup** [comment]
I have a feeling I'm getting the same issue on Debian 12 Bookworm, Docker Compose version v2.29.2, Latest declutarr docker image as of time of posting:

I get the following error using the example docker-compose.yaml from https://github.com/ManiMatter/decluttarr/ 

`decluttarr  | [ ERROR ]: The value retrieved for [feature_settings]: IGNORED_DOWNLOAD_CLIENTS is "emulerr" and cannot be converted to data type <class 'list'>`

After removing the "" marks around emulerr in the docker-compose.yaml file, eg.

`IGNORED_DOWNLOAD_CLIENTS: [emulerr]`

 The following error was received:

`validating docker-compose.yaml: services.decluttarr.environment.IGNORED_DOWNLOAD_CLIENTS must be a string, number, boolean or null`

I tried a few other variations but couldn't find an argument that passed both checks.

Removing the line containing `IGNORED_DOWNLOAD_CLIENTS` completely allowed docker compose to start the container.

Not an issue for me personally as I'm not planning to ignore any download clients at the moment, I just thought you might like to know about it.

Cheers.


Steps to reproduce:
A) Save the example docker-compose.yaml from https://github.com/ManiMatter/decluttarr/ and run `docker compose up`
B) Remove the quotation marks from the line `IGNORED_DOWNLOAD_CLIENTS: ["emulerr"]`, save the file and run `docker compose up`

**Comment by Xeboc** [comment]
The example in the Readme could be updated.  The [FAILED_IMPORT_MESSAGE_PATTERNS](https://github.com/ManiMatter/decluttarr/blob/dev/README.md?plain=1#L97-L101) example shows how this could be written to both pass the docker compose validation and still be used:

```
IGNORED_DOWNLOAD_CLIENTS: '["emulerr"]'
```
