### ISSUE TITLE
Not all cases of "Missing Files" are caught. 

### ISSUE THREAD

**Issue by mels0n** [ManiMatter/decluttarr#216]
qBittorent version 5.0.2
Radarr version 5.15.1.9463

Items in queue that are not private and had 'Missing Files' errors are not being cleaned up.

Was able to troubleshoot by adding additional debug logging locally, inside the loop for the remove missing script.

  `          logger.debug("Checking queue item: %s", queueItem)  # Log the entire queue item`

Results:
`
[DEBUG]: Checking queue item: {'movieId': 1962, 'languages': [{'id': 1, 'name': 'English'}], 'quality': {'quality': {'id': 7, 'name': 'Bluray-1080p', 'source': 'bluray', 'resolution': 1080, 'modifier': 'none'}, 'revision': {'version': 1, 'real': 0, 'isRepack': False}}, 'customFormats': [{'id': 131, 'name': '5.1 Surround'}, {'id': 133, 'name': 'DD'}], 'customFormatScore': 750, 'size': 17432508998, 'title': 'RemovedFileName', 'sizeleft': 17432508998, 'added': '2024-12-16T05:47:37Z', 'status': 'warning', 'trackedDownloadStatus': 'ok', 'trackedDownloadState': 'downloading', 'statusMessages': [], 'errorMessage': 'qBittorrent is reporting missing files', 'downloadId': 'B1F6E6019AD8633C5941A6E14F7DFD4C7A905A26', 'protocol': 'torrent', 'downloadClient': 'qBittorrent', 'downloadClientHasPostImportCategory': True, 'indexer': 'RemovedIndexer', 'id': 1143668024}`

In local testing following the same logic that exits in the script the below fixes the problem.

`or queueItem["errorMessage"] == "qBittorrent is reporting missing files"`

**Comment by mels0n** [comment]
If you'd like a PR for debugging enhancement I have can toss one in with the below in each of the remove loops.
`logger.debug("Checking queue item: %s", queueItem)  # Log the entire queue item`

**Comment by nathang21** [comment]
FYI there may be a bug with this, I have torrents that are fully downloaded (only a single file) and seeding getting removed due to "missing files" from Radarr. I'm mobile right now so don't have debug logs but if I can reproduce will open an issue.
