### ISSUE TITLE
Queue cleaning failed on Radarr

### ISSUE THREAD

**Issue by samcro1967** [ManiMatter/decluttarr#23]
I have a download in radarr that is stuck at `pending`.  I get the error message below in the docker logs.

Docker compose
```
  decluttarr:
    hostname: decluttarr
    image: ghcr.io/manimatter/decluttarr:latest   
    container_name: decluttarr
    restart: always
    environment:
       - TZ=${TZ}
       - PUID=${PUID}
       - PGID=${PGID}
      # General
       - LOG_LEVEL=VERBOSE
      #TEST_RUN: True 
      # Features 
       - REMOVE_TIMER=10
       - REMOVE_FAILED=True
       - REMOVE_STALLED=True
       - REMOVE_METADATA_MISSING=True     
       - REMOVE_ORPHANS=True
       - REMOVE_UNMONITORED=True
       - PERMITTED_ATTEMPTS=3
       - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill If Stalled
      # Radarr
       - RADARR_URL=http://192.168.1.104:8095/radarr
       - RADARR_KEY=$RADARR_API_KEY
      # Sonarr
       - SONARR_URL=http://192.168.1.104:8079/sonarr
       - SONARR_KEY=$SONARR_API_KEY
      # Lidarr
       - LIDARR_URL=http://192.168.1.104:8686/lidarr
       - LIDARR_KEY=$LIDARR_API_KEY    
      # qBitorrent
       - QBITTORRENT_URL=http://192.168.1.104:8113
       - QBITTORRENT_USERNAME=$USER
       - QBITTORRENT_PASSWORD=$PASSWORD
```

Docker logs
```
[INFO   ]: ##################################################
[INFO   ]: Application Started!
[INFO   ]:
[INFO   ]: *** Current Settings ***
[INFO   ]: True | Removing failed downloads
[INFO   ]: True | Removing stalled downloads
[INFO   ]: True | Removing downloads missing metadata
[INFO   ]: True | Removing orphan downloads
[INFO   ]: True | Removing downloads belonging to unmonitored TV shows/movies
[INFO   ]:
[INFO   ]: Running every: 0 days 0 hours 10 minutes
[INFO   ]: Permitted number of times before stalled/missing metadata downloads are removed: 3
[INFO   ]: Downloads with this tag will be skipped: "Don't Kill If Stalled"
[INFO   ]:
[INFO   ]: *** Configured Instances ***
[INFO   ]: Radarr: http://192.168.1.104:8095/radarr/api/v3
[INFO   ]: Sonarr: http://192.168.1.104:8079/sonarr/api/v3
[INFO   ]: Lidarr: http://192.168.1.104:8686/lidarr/api/v1
[INFO   ]: qBittorrent: http://192.168.1.104:8113/api/v2
[INFO   ]:
[INFO   ]: *** Check Instances ***
[INFO   ]: OK | Radarr
[INFO   ]: OK | Sonarr
[INFO   ]: OK | Lidarr
[INFO   ]: OK | qBittorrent
[INFO   ]:
[INFO   ]: ##################################################
[INFO   ]:
[VERBOSE]: --------------------------------------------------
[VERBOSE]: Cleaning queue on Radarr:
[WARNING]: >>> Queue cleaning failed on Radarr. (File: queue_cleaner.py / Line: 233 / Error Message: 'downloadId' / Error Type: <class 'KeyError'>)
[VERBOSE]: Cleaning queue on Sonarr:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]: Cleaning queue on Lidarr:
[VERBOSE]: >>> Queue is empty.
[VERBOSE]:
[VERBOSE]: Queue clean-up complete!
```

**Comment by ManiMatter** [comment]
Can you upgrade to the nightly (rather than latest) versions of sonarr/radarr/lidarr, and update qbit to the latest version (if not already)?

**Comment by samcro1967** [comment]
I am already using nightly for radarr and latest for qbit.  Sonarr and Lidarr are on latest, but they are working.

**Comment by ManiMatter** [comment]
Could you please set the debug level to "DEBUG" and paste the log in a pastebin?
Also could you please share a screenshot of how qbit & radarr queue look?

**Comment by samcro1967** [comment]
Currently unable to pull the decluttarr image.  Appears to be an issue with the manifests for latest and v1.21.0.  Dev is working.

**docker run --rm quay.io/skopeo/stable list-tags docker://ghcr.io/manimatter/decluttarr**

{
    "Repository": "ghcr.io/manimatter/decluttarr",
    "Tags": [
        "latest",
        "v0.11.0",
        "v0.12.0",
        "v0.13.0",
        "v0.14.0",
        "v1.0.0",
        "v1.1.0",
        "v1.2.0",
        "v1.3.0",
        "v1.4.0",
        "v1.5.0",
        "v1.7.0",
        "v1.8.0",
        "v1.9.0",
        "v1.10.0",
        "v1.11.0",
        "v1.12.0",
        "v1.13.0",
        "v1.14.0",
        "v1.15.0",
        "v1.16.0",
        "dev",
        "v1.17.0",
        "v1.18.0",
        "v1.19.0",
        "v1.19.1",
        "v1.20.0",
        "v1.21.0"
    ]
}

**$ docker run --rm quay.io/skopeo/stable inspect docker://ghcr.io/manimatter/decluttarr:latest**

time="2024-02-17T18:28:59Z" level=fatal msg="Error parsing manifest for image: fetching target platform image selected from image index: reading manifest sha256:702c2e03c54f5116f649fcaf538e083daa3c22a77ac73d937b52004a19265920 in ghcr.io/manimatter/decluttarr: manifest unknown"


**$ docker run --rm quay.io/skopeo/stable inspect docker://ghcr.io/manimatter/decluttarr:v1.21.0**

time="2024-02-17T18:29:05Z" level=fatal msg="Error parsing manifest for image: fetching target platform image selected from image index: reading manifest sha256:702c2e03c54f5116f649fcaf538e083daa3c22a77ac73d937b52004a19265920 in ghcr.io/manimatter/decluttarr: manifest unknown"


**$ docker run --rm quay.io/skopeo/stable inspect docker://ghcr.io/manimatter/decluttarr:dev**

{
    "Name": "ghcr.io/manimatter/decluttarr",
    "Digest": "sha256:f9bce080ee8249f8da35c22aaee069e0b47c356caf8e88f5ac027eed437ab88e",
    "RepoTags": [
        "latest",
        "v0.11.0",
        "v0.12.0",
        "v0.13.0",
        "v0.14.0",
        "v1.0.0",
        "v1.1.0",
        "v1.2.0",
        "v1.3.0",
        "v1.4.0",
        "v1.5.0",
        "v1.7.0",
        "v1.8.0",
        "v1.9.0",
        "v1.10.0",
        "v1.11.0",
        "v1.12.0",
        "v1.13.0",
        "v1.14.0",
        "v1.15.0",
        "v1.16.0",
        "dev",
        "v1.17.0",
        "v1.18.0",
        "v1.19.0",
        "v1.19.1",
        "v1.20.0",
        "v1.21.0"
    ],
    "Created": "2024-02-17T16:21:52.732976779Z",
    "DockerVersion": "",
    "Labels": {
        "org.opencontainers.image.source": "https://github.com/ManiMatter/decluttarr"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e1caac4eb9d2ec24aa3618e5992208321a92492aef5fef5eb9e470895f771c56",
        "sha256:51d1f07906b71fd60ac43c61035514996a8ad8dbfd39d4f570ac5446b064ee5d",
        "sha256:c0d8da8ab021fce179c54d4f899b83f7fdb5d5bd7ec73b737bcb3f60c00908f9",
        "sha256:ce524da9d5723ff0cc7d540777cd1202c07fad525cfada0c16924d447d482d5f",
        "sha256:d0d45da63dd11d6510595eb29c9614e5f3e669e38bfbf94a362ff156d81739ca",
        "sha256:af6b53ae152a8040cef5939482a918faaf88e0919e83ddffc1f1c4d1888f2fae",
        "sha256:4578a6cc41768106a513530980f61a9bd14daba42698d7097f34f64cefb33c38",
        "sha256:0870df5cd99235b13a1be9202739af01b30a782b90f23644bd000619d926cd12"
    ],
    "LayersData": [
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:e1caac4eb9d2ec24aa3618e5992208321a92492aef5fef5eb9e470895f771c56",
            "Size": 29124091,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:51d1f07906b71fd60ac43c61035514996a8ad8dbfd39d4f570ac5446b064ee5d",
            "Size": 3507732,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:c0d8da8ab021fce179c54d4f899b83f7fdb5d5bd7ec73b737bcb3f60c00908f9",
            "Size": 12377016,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:ce524da9d5723ff0cc7d540777cd1202c07fad525cfada0c16924d447d482d5f",
            "Size": 242,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:d0d45da63dd11d6510595eb29c9614e5f3e669e38bfbf94a362ff156d81739ca",
            "Size": 3363776,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:af6b53ae152a8040cef5939482a918faaf88e0919e83ddffc1f1c4d1888f2fae",
            "Size": 93,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:4578a6cc41768106a513530980f61a9bd14daba42698d7097f34f64cefb33c38",
            "Size": 72434,
            "Annotations": null
        },
        {
            "MIMEType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
            "Digest": "sha256:0870df5cd99235b13a1be9202739af01b30a782b90f23644bd000619d926cd12",
            "Size": 7251155,
            "Annotations": null
        }
    ],
    "Env": [
        "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "LANG=C.UTF-8",
        "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D",
        "PYTHON_VERSION=3.10.13",
        "PYTHON_PIP_VERSION=23.0.1",
        "PYTHON_SETUPTOOLS_VERSION=65.5.1",
        "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py",
        "PYTHON_GET_PIP_SHA256=dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9",
        "IS_IN_DOCKER=1"
    ]
}
```

**Comment by ManiMatter** [comment]
@samcro1967  - Thanks for the above - I think I fixed the problem with yesterday's release. Please let me know if you still have issues.

Has your original issue been solved?

**Comment by samcro1967** [comment]
Manifest is working now.  I am able to pull the latest image.  Will monitor and see if I can reproduce tis issue now or if it is resolved.

**Comment by ManiMatter** [comment]
Hi @samcro1967 
Just checking if your issue is resolved and whether this ticket can be closed?

**Comment by samcro1967** [comment]
I have yet to see a reoccurrence so will close.
