### ISSUE TITLE
please support transmission as torrent client

### ISSUE THREAD

**Issue by spupuz** [ManiMatter/decluttarr#40]
please support transmission as torrent client

**Comment by ManiMatter** [comment]
Any client is supported, just not with all features (any that require direct connection; 1) dont-kill flag, 2. real-time speed detection for slowness; inaccurate slowness detection works though)

no plan to extend decluttarr beyond this; happy to accept a PR though

**Comment by spupuz** [comment]
what about all the torrents added but that do not shows in radarr and never ever strart in the torrent client (transmission in mycase) or seed downloads that never have uploads and never reach the ration?

**Comment by ManiMatter** [comment]
I see you found the answer already:
https://github.com/Prowlarr/Prowlarr/issues/1928
