### ISSUE TITLE
Log claims qBittorrent is outdated

### ISSUE THREAD

**Issue by Hutch79** [ManiMatter/decluttarr#53]
With the newer versions of decluttarr i've noticed that it doesn't want to connect to my qBittorrent instance, since it's outdated.  
Im on version 4.6.0 which gets correctly recognized in the log message and it asks me to update to 4.6.0 which is the same version.  
`Error: Please update qBittorrent to at least version 4.6.0. Current version: 4.6.0`  

This happens since at least v1.25.0. I've tested older versions, but the next lower version is already v1.20.0 which can establish a connection with no problems.  

I've also tested an updated version of qBit (v4.6.2) which also gets recognized correctly in the log message, but it also does not work.
`Error: Please update qBittorrent to at least version 4.6.0. Current version: 4.6.2`

I'm honestly out of ideas on what to test.  
Therefore, I would be glad for help and in the meantime use v1.20.0 of decluttarr.  

Thanks for your help and work on the project!

**Comment by Shane091490** [comment]
I'm having similar issue, Declutter will not run. It says that my qBittorrent is out of date in the logs.

Environment: Docker
Declutter version: 1.28.1
qBittorrent version: 4.3.8
qBittorrent image: markusmcnugen/qbittorrentvpn

I don't see a recommended qb image or required version in the repo, I use this qb for it's vpn functions.

Let me know if there is anything I can do to help. I love this solution, we really need something like this.

**Comment by ManiMatter** [comment]
Thank you for raising this; I will take a look!

**Comment by ManiMatter** [comment]
Created PR - should fix your problems; pls let me know if after pulling the newest 'latest' image you still have issues

**Comment by Shane091490** [comment]
Just pulled the latest image and it is running now. Thanks!

**Comment by Hutch79** [comment]
Same here, running perfectly now.
Thanks very much for the fast fix!
