### ISSUE TITLE
TypeError on Start (unsupported operand)

### ISSUE THREAD

**Issue by Shane091490** [ManiMatter/decluttarr#58]
Hey, 

So trying to setup a Decluttarr instance for Sonarr but keep getting this TypeError. My Radarr instance is working.

I have two different VM's one for Radarr and one for Sonarr because I needed two instances of qBittorrent to separate movies and tv.

I thought it was my compose file at first but i'm confident that's not the issue now. I don't know why this is happening.

![image](https://github.com/ManiMatter/decluttarr/assets/26034295/af32e3a1-e5ff-4435-8545-13f04cf48a9a)

version: "3.3"
services:
    sonarr-decluttarr:
      image: ghcr.io/manimatter/decluttarr:latest
      container_name: sonarr-decluttarr
      restart: always
      environment:
        - TZ=America/Chicago
        - PUID=1000
        - PGID=1000
        ## General
        - LOG_LEVEL=VERBOSE
        #- TEST_RUN=True
        #- SSL_VERIFICATION=False
        ## Features 
        - REMOVE_TIMER=10
        - REMOVE_FAILED=True
        - REMOVE_METADATA_MISSING=True
        - REMOVE_MISSING_FILES=True     
        - REMOVE_ORPHANS=True
        - REMOVE_SLOW=False
        - REMOVE_STALLED=True
        - REMOVE_UNMONITORED=True
        #- MIN_DOWNLOAD_SPEED=100
        - PERMITTED_ATTEMPTS=3
        - NO_STALLED_REMOVAL_QBIT_TAG=Don't Kill
        - IGNORE_PRIVATE_TRACKERS=True
        ## Sonarr
        - SONARR_URL=https://sonarr.myrealm.site
        - SONARR_KEY=e1f4a15d1f594487ade60439e3020336
        ## qBittorrent
        - QBITTORRENT_URL=https://sqbit.myrealm.site
        - QBITTORRENT_USERNAME=Removed
        - QBITTORRENT_PASSWORD=Removed

**Comment by ManiMatter** [comment]
Id need the dev-image debug logs again pls

**Comment by Shane091490** [comment]
I get the same result when I run in dev and debug.

**Comment by ManiMatter** [comment]
Ah you don‘t even get logs?!

**Comment by Shane091490** [comment]
Nope, no logs at all just that error.

**Comment by ManiMatter** [comment]
Would you mind downloading the repo and running main.py manually? Maybe that spits out a helpful error

**Comment by ManiMatter** [comment]
I think I solved it - could you please pull the dev image and verify?

**Comment by ManiMatter** [comment]
Closing since considered fixed. pls shout if not the case.
