### ISSUE TITLE
Manifest unknown when pulling latest

### ISSUE THREAD

**Issue by riddertommie** [ManiMatter/decluttarr#65]
Hello, I'm getting below error 

```
Failure
failed to deploy a stack: decluttarr Pulling manifest unknown
```

i'm using: image: ghcr.io/manimatter/decluttarr:latest

Looked at the previous Issue #64 concerning 

> Manifest unknown when pulling latest 

Looks almost the same but does not give a solution

I'm i doing something wrong?

**Comment by ManiMatter** [comment]
Same as #64 - we hope we can fix this in the next days, apols

**Comment by riddertommie** [comment]
NP, Thanks!
