### ISSUE TITLE
[Feature request] remove 0% download from private tracker 

### ISSUE THREAD

**Issue by oliroe** [ManiMatter/decluttarr#71]
Hi

Awesome app by the way. I have a scenario that isn't covered by the available options. Quite often I'll have a download from a private tracker that never downloads anything. I 'd like the option of removing these entries which won't risk a Hit 'n' Run. Currently there's only an options for stalled downloads that may have partially downloaded

Thanks

**Comment by ManiMatter** [comment]
Can you pls provide a screenshot of such torrent in qbit?

**Comment by ManiMatter** [comment]
ping?

**Comment by oliroe** [comment]
> ping?

Apologies, don't have an example right now but trying to reproduce it. Happy to close and create a new one when I have something concrete
