### ISSUE TITLE
How does it handle qBittorrent queueing

### ISSUE THREAD

**Issue by HomebrewDotNET** [ManiMatter/decluttarr#74]
I was wondering how declutarr handles torrent queueing. Could't find anything in the documentation (or I missed it)
Does it also tag them as stalled?

**Comment by ManiMatter** [comment]
It does not handle queues at all. 

In my own setup I download everything in parallel. If you chose to queue, what would you expect decluttarr do for you?

**Comment by HomebrewDotNET** [comment]
Well I'm currently running without queue as well with Decluttarr (And it's running great btw, nice job :D)

Been looking getting an ssd for my setup but noticed my in progress folder is 2TB+ so queueing should decrease this size at the same time.

Now on how to handle this is quite an annoying issue since I don't think qBit exposes a queued status for downloading torrents. So I guess you'd need to check how many torrents are 'Active' and only start deleting/removing if the active amount of torrents falls below a threshold. Because then we can assume the stalled torrents are actually stalled and nog 'Queued'

But as I said an annoying issue to deal with so I don't expect you to fix this. Was just wondering :)

**Comment by ManiMatter** [comment]
> Well I'm currently running without queue as well with Decluttarr (And it's running great btw, nice job :D)


thx :)

re queueing: queue all you want, nothing stops you from doing so ;) and decluttarr should still work as expected.
decluttarr does not mess with queued items; only those that are in specific states (such as stalled, or downloading too slow) get whacked. 

suggest you simply try it out; enable queueing and you'll see that they will be left in peace whilst they are queued.

**Comment by HomebrewDotNET** [comment]
Ok cool. Good to know. Thanks!
