### ISSUE TITLE
[Feature Request] Log "log" onto a log file

### ISSUE THREAD

**Issue by alexx-ftw** [ManiMatter/decluttarr#80]
If for whatever reason the script is forcefully closed, crashes , etc, the log is lost.

Can you please log the "log" text onto a log file?

**Comment by ManiMatter** [comment]
hi @alexx-ftw 
I see where you are coming from. 

Not planning to add this though (since I don't see the value in retaining the logs), but happy to review a PR if you'd like to code this

**Comment by ManiMatter** [comment]
Closed as no feedback / not planned
