### ISSUE TITLE
[Feature request] Support for multiple arr instances

### ISSUE THREAD

**Issue by SixFive7** [ManiMatter/decluttarr#96]
It would be nice if we could define multiple Radarr (or Sonarr) url's and API keys for those who are running multiple instances. Right now one would have to run multiple decluttarr and qbitorrent instances. The latter brings bandwidth management and VPN complexities.
Some context: https://trash-guides.info/Radarr/Tips/Sync-2-radarr-sonarr/

**Comment by ManiMatter** [comment]
Not planned for three reasons:
1) a worksround exists (multiple instances)
2) would be a significant rewrite
3) radarr/sonarr said they may support multiple qualities in a single instance in the future

**Comment by SixFive7** [comment]
Three very valid reasons. Thank you for responding quickly and thank you for decluttarr in general!
